### ISSUE TITLE
Pressing 'zf' in quickfix throw error

### ISSUE THREAD

**Issue by smpchandru** [kevinhwang91/nvim-bqf#10]
Error : E5108: Error executing lua ...e/nvim/site/pack/packer/start/nvim-bqf/lua/bqf/utils.lua:18: attempt to perform arithmetic on local 'color_num' (a nil value)

Looks like : 
Function 'color2csi24b' expect argument, but in 'local color2csi = gui and color2csi24b or color2csi8b '  not passing arg

**Comment by kevinhwang91** [comment]
Could you privode what the output of
```vim
echo nvim_get_hl_by_name('BqfSign', 1)
echo nvim_get_hl_by_name('qfFileName', 1)
echo nvim_get_hl_by_name('qfLineNr', 1)
echo nvim_get_hl_by_name('qfSeparator', 1)
echo nvim_get_hl_by_name('qfError', 1)
```

**Comment by smpchandru** [comment]
E5555: API call: Invalid highlight name: BqfSign
E5555: API call: Invalid highlight name: qfFileName
E5555: API call: Invalid highlight name: qfLineNr
E5555: API call: Invalid highlight name: qfSeparator
E5555: API call: Invalid highlight name: qfError

**Comment by kevinhwang91** [comment]
It's so weird. qf highlight group is defined in `nvim/runtime/syntax/qf.vim`. I think you should check out your color theme whether clear/unlink these highlights.

In bqf, it will eat these errors in the later patch.

**Comment by smpchandru** [comment]
Let me check that

**Comment by kevinhwang91** [comment]
I have updated the repo, you could update and give me more feedback.

**Comment by smpchandru** [comment]
Great it fixed.... Thank you so much 
I have one more problem with respect fzf location list where both fzflist and qbf quiickfix list opens when we do coc_reference

**Comment by kevinhwang91** [comment]
Could you describe it in more detail? I can't get your point. A screenshot or a record is better.

**Comment by smpchandru** [comment]
Created video which dipicts problem... not sure how to attch the same here

**Comment by smpchandru** [comment]
[](url

https://user-images.githubusercontent.com/28723442/112714987-50e83080-8f03-11eb-91e6-2eb6973e9015.mp4

)

**Comment by kevinhwang91** [comment]
I see, you mean make bqf get along with https://github.com/antoinemadec/coc-fzf.

**Comment by kevinhwang91** [comment]
You can use `au! CocFzfLocation User CocLocationsChange` to disable `CocLocationsChange` event of coc-fzf.

**Comment by smpchandru** [comment]
Was trying this option as per the readme, not sure is this same as above


  let g:coc_enable_locationlist = 0    
  autocmd User CocLocationsChange ++nested call Coc_qf_jump2loc(g:coc_jump_locations)      chadrappa | 3 days ago | Initial step to migrate vimscr
      
  nmap <silent> gr <Plug>(coc-references)    
  nnoremap <silent> <leader>qd <Cmd>call Coc_qf_diagnostic()<CR>

**Comment by kevinhwang91** [comment]
Add `au VimEnter * au! CocFzfLocation User CocLocationsChange` will work.

**Comment by smpchandru** [comment]
Thanks a lot..
