### ISSUE TITLE
Window-picker integration

### ISSUE THREAD

**Issue by sarmong** [kevinhwang91/nvim-bqf#100]
### Feature description

There is a [window-picker plugin](https://github.com/s1n7ax/nvim-window-picker) that allows you to select which window you want to open the file in.

I want to make it work with bqf.

### Describe the solution you'd like

Pretty much doing this does the trick.

 https://github.com/kevinhwang91/nvim-bqf/blob/d15b59d7429d45f0b057aa63a0266989adc95715/lua/bqf/qfwin/handler.lua#L184-L184
 
```diff
-    -- local pwinid = qs:previousWinid()
+   local pwinid = require("window-picker").pick_window()
+   if not pwinid then
+      return
+   end
```

### Additional context

I am willing to contribute, but I want you opinion on how to make it work architecturally. Provide a separate function that can be mapped to a key? Or make a user provide their own custom function that selects a window to not be dependent on specific plugin?

Also, there should be a way to hide preview when selecting a window, because it covers part of the file.

**Comment by kevinhwang91** [comment]
Make sense, add a cb func like `pick_window` return a window id in the root setup table is not bad.

**Comment by kevinhwang91** [comment]
```lua
---@param qf_type string|'quickfix'|'location'
---@param action string|'open'|'openc'|'drop'|'tabdrop'|'tab'|'tabb'|'tabc'|'split'|'vsplit'
---@param default_winid number
---@return number
function pick_window(qf_type, action, default_winid) end
```
This is the function signature I draft, feel free to show your opinion in PR.

**Comment by sarmong** [comment]
```
---@param action string|'open'|'openc'|'drop'|'tabdrop'|'tab'|'tabb'|'tabc'|'split'|'vsplit'
```

I don't think this function has to work for anything but `open` and `openc`.

If I understand you correctly, you want the following - if this function was provided in user config - use it to determine window, otherwise fall back to `previousWinid`. 
However, I want to have 2 separate mappings, e.g. `<CR>` - regular `open`, `<C-CR>` - pick window and open.

I don't see how this will be achievable with this setup.

We could add a new function `open_in` that uses user-provided `pick_window` function to determine the window. However, then we would need to provide `open_in_and_close` or `openc_in`, if someone wants to close the quickfix after picking the window. 
I am not sure it it's a good solution.

**Comment by kevinhwang91** [comment]
> I don't see how this will be achievable with this setup.

Yes

The `func_map` is a `table<string, string>` type and must concatenate func actions to string as key.

Maybe hacking yourself is better.

```lua
    -- In ftplugin/qf.lua
        vim.cmd('norm p')
        local winid = require('window-picker').pick_window()
        vim.cmd('norm p')
        if not winid then
            return
        end
        local cursor = vim.api.nvim_win_get_cursor(0)
        vim.fn.setqflist({}, 'r', {idx = cursor[1]})
        vim.api.nvim_set_current_win(winid)
        vim.cmd('cc')
```

**Comment by sarmong** [comment]
Doing `vim.cmd('norm p')` is not a good solution because if you have closed the preview, it will just open it.

Would be nice to have an exported api function to disable preview. (Not sure if it's safe to use internal functions)

**Comment by kevinhwang91** [comment]
Added `hidePreviewWindow` and `showPreviewWindow` API.
```lua
 vim.keymap.set('n', 'O', function()
    local showed = require('bqf').hidePreviewWindow()
    local winid = require('window-picker').pick_window()
    if not winid then
        if showed then
            require('bqf').showPreviewWindow()
        end
        return
    end
    local cursor = vim.api.nvim_win_get_cursor(0)
    vim.fn.setqflist({}, 'r', {idx = cursor[1]})
    vim.api.nvim_set_current_win(winid)
    vim.cmd('cc')
end, {buffer = true})
```
