### ISSUE TITLE
moudle "bqf" not found

### ISSUE THREAD

**Issue by xieping5555** [kevinhwang91/nvim-bqf#102]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.0-dev-771+g18fb669b9-dirty

### Operating system/version

macOS 12.0.1

### How to reproduce the issue

1. use packer.nvim install the plugin
2. run `:lua require('bqf')` in neovim command mode
3.
...

### Expected behavior

module bqf load correctly

### Actual behavior

<img width="655" alt="image" src="https://user-images.githubusercontent.com/24475843/215651880-af61680e-a57a-4b56-9cf4-f706f1bf7ab1.png">

**Comment by sarmong** [comment]
Try `:PackerCompile`
