### ISSUE TITLE
Fzf-lua function routines

### ISSUE THREAD

**Issue by RayZ0rr** [kevinhwang91/nvim-bqf#103]
### Feature description

Right now we have to install fzf.vim because bqf is using some of its functions like `fzf#run`

But would it be possible to use `fzf_exec` from fzf-lua instead?

### Describe the solution you'd like

Make use of `fzf_exec` to utilise the `opts` table handed over to `fzf#run`

**Comment by kevinhwang91** [comment]
bqf requires `fzf#run` in `fzf` .   https://github.com/kevinhwang91/nvim-bqf/issues/83 and https://github.com/kevinhwang91/nvim-bqf/issues/73 are related.

**Comment by RayZ0rr** [comment]
Hi,

I already saw those issues. However, what I wanted to ask was whether it's possible to use `fzf-exec` from Fzf-lua instead of `fzf#run` if it is present.

**Comment by kevinhwang91** [comment]
Yes, PR is welcome.
