### ISSUE TITLE
possible to rename the list?

### ISSUE THREAD

**Issue by MagicDuck** [kevinhwang91/nvim-bqf#105]
### Feature description

Wonder if it it's possible to rename the lists. Atm it's possible to navigate multiple lists with `<` and `>` (or Telescope quickfixhistory), but it can get confusing if they have similar names. Would be nice to have the ability to rename the lists.

Thank you in advance!

### Describe the solution you'd like

If it's not currently available, it would be probably best to surface it as a command (:BqfRenameList) or keybinding (r - rename???)

**Comment by kevinhwang91** [comment]
call setqflist([], 'r', {'title': 'amIGoodEnough?'})

**Comment by MagicDuck** [comment]
exactly what I was looking for, thank you so much! I spent like 20min trawling through the nvim quickfix list docs, but this did not pop out to me!
