### ISSUE TITLE
Scroll issue w/ Preview On and 'scrolloff' set to half the qf window height

### ISSUE THREAD

**Issue by MunifTanjim** [kevinhwang91/nvim-bqf#112]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0-dev-1768+gc48f94d1f-Homebrew

### Operating system/version

macOS 13.4

### How to reproduce the issue

1. Open a quickfix window with enough items to scroll through (30+)
2. Make sure the preview is always on (i.e. moving up/down in qf window changes preview)
3. Make sure qf window height is displaying exactly 8 items
4. Run `:set scrolloff=4`
5. Now move up/down in qf window
6. The cursorline in qf window and preview window will not be in sync

This is also reproducible when qf window height is 10 and scrolloff=5 (i.e. half of height).

### Expected behavior

Preview and cursorline should be in sync.

### Actual behavior

![Kapture 2023-06-08 at 02 01 33](https://github.com/kevinhwang91/nvim-bqf/assets/8050659/a210c2ee-ac25-4040-aabf-530ae7886fa4)

**Comment by kevinhwang91** [comment]
Can't reproduce it. From your image, look like your script change the qf window view. Just like setting `scrolloff=4`, and typing `jk`.

**Comment by MunifTanjim** [comment]
Can you put this in a `minimal_init.lua` file:

```lua
local M = {}

function M.root(root)
  local f = debug.getinfo(1, "S").source:sub(2)
  return vim.fn.fnamemodify(f, ":p:h") .. "/" .. (root or "")
end

---@param plugin string
function M.load(plugin)
  local name = plugin:match(".*/(.*)")
  local package_root = M.root(".repro/site/pack/deps/start/")
  if not vim.loop.fs_stat(package_root .. name) then
    print("Installing " .. plugin)
    vim.fn.mkdir(package_root, "p")
    vim.fn.system({
      "git",
      "clone",
      "--depth=1",
      "https://github.com/" .. plugin .. ".git",
      package_root .. "/" .. name,
    })
  end
end

function M.setup()
  vim.cmd([[set runtimepath=$VIMRUNTIME]])
  vim.opt.runtimepath:append(M.root())
  vim.opt.packpath = { M.root(".repro/site") }
  M.load("kevinhwang91/nvim-bqf")
  vim.env.XDG_CONFIG_HOME = M.root(".repro/config")
  vim.env.XDG_DATA_HOME = M.root(".repro/data")
  vim.env.XDG_STATE_HOME = M.root(".repro/state")
  vim.env.XDG_CACHE_HOME = M.root(".repro/cache")
end

M.setup()

vim.o.splitkeep = "screen"
vim.o.scrolloff = 5

require("bqf").setup({})

vim.cmd("vimgrep v %")

vim.cmd("copen")
```

Then run:
```sh
nvim -u NORC -u minimal_init.lua minimal_init.lua
```

And try again?

Anyway, I don't think this is an issue with this plugin anymore.

It's a Neovim issue with `splitkeep = "screen"`.

Thanks for this nice plugin! 😃

**Comment by MunifTanjim** [comment]
I can't replicate with without the preview window from `bqf`. So not sure if it's a Neovim issue. I'd really appreciate if you try once more with the minimal config I posted in the comment above.
