### ISSUE TITLE
Preview window is transparent and ignores `winblend` and `pumblend`

### ISSUE THREAD

**Issue by BStephenBB** [kevinhwang91/nvim-bqf#114]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.0

### Operating system/version

macOS 13.4

### How to reproduce the issue

1. Search for something with `:Rg 'foobar'`
2. Observe transparent preview window:
![image](https://github.com/kevinhwang91/nvim-bqf/assets/36211879/03f6534c-31bc-4ee8-9d50-e11585c33cdc)

I haven't tried making a minimal reproduction of this yet, happy to try and do that later when I have more time -- wanted to flag this for now since I started noticing it probably a week or two ago and the preview window was never transparent before.

I have `winblend` and `pumblend` set to 0 in my config, but that doesn't seem to help. I checked bqf's settings for an option that might set this, but didn't see anything. Apologies if I missed something. This would probably be a cool option to allow users to configure, I personally don't like the transparency though since it makes the code in the preview window harder to read.

I'm using Kitty for my terminal and am on `0.27.0` in case that helps too. 

### Expected behavior

I don't expect the preview window to be transparent.

### Actual behavior

The preview window is transparent.

**Comment by rockyzhang24** [comment]
Follow the documentation (README) please:

```lua
require('bqf').setup {
  preview = {
    winblend = 0,
  }
}
```

**Comment by BStephenBB** [comment]
Ah, I missed this, sorry. Will close this issue. Thanks!
