### ISSUE TITLE
is there a way to start in fzf mode automatically?

### ISSUE THREAD

**Issue by alok** [kevinhwang91/nvim-bqf#12]
the title^

**Comment by kevinhwang91** [comment]
No, but I will add an option for this:)

**Comment by kevinhwang91** [comment]
For now, I think nvim-bqf shouldn't make this feature as builtin. But users can do what they want in below 2 ways:

## global qf
`echo "call feedkeys('zf', 'm')" >> your_path/nvim/after/ftplugin/qf.vim` 

## local qf
append `call feedkeys('zf', 'm')` cmd to you personal command like `cw`

> You can also do this in lua, enjoy yourself :)
