### ISSUE TITLE
fzf filter window broken

### ISSUE THREAD

**Issue by Subjective** [kevinhwang91/nvim-bqf#123]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0-dev-bb38c06

### Operating system/version

macOS 13.4

### How to reproduce the issue

1. Open the filter window
2. Type in a query
3. Scroll through
4. Random artifacts like flickering, multiple/jumping cursors, visually unable to scroll to bottom of list

### Expected behavior

![Screen Recording 2023-09-10 at 1 49 51 PM](https://github.com/kevinhwang91/nvim-bqf/assets/56745535/a17b1f6a-7c2a-4d91-94ea-b169e1d81876)

### Actual behavior

I ran a git bisect and it seems like ever since e9102f15387e76dd898f6d1aa3e66a1d2f88d1f7, the fzf filter function has been somewhat broken (see gif and screenshots below).

![Screen Recording 2023-09-10 at 1 41 48 PM](https://github.com/kevinhwang91/nvim-bqf/assets/56745535/db01c467-b677-4a57-845c-4ccda78262d9)

<img width="815" alt="image" src="https://github.com/kevinhwang91/nvim-bqf/assets/56745535/154d30ff-8d42-4332-a829-add315d9ec0d">

**Comment by kevinhwang91** [comment]
Can't reproduce it under v0.9.2, look like a bug of core.

**Comment by Subjective** [comment]
> Can't reproduce it under v0.9.2, look like a bug of core.

Yeah you're right, it doesn't happen on neovim stable weirdly enough.

**Comment by kevinhwang91** [comment]
Leave this issue open, and wait for the next stable release.

**Comment by Subjective** [comment]
Interestingly enough, this issue only seems to happen when the preview is shown.
