### ISSUE TITLE
Adjusting the height of the qf window doesn't reposition the preview correctly

### ISSUE THREAD

**Issue by Subjective** [kevinhwang91/nvim-bqf#126]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0-dev-be10d65

### Operating system/version

macOS 13.4

### How to reproduce the issue

1. `:copen`
2. Hit `<c-w>-`/`<c-w>+` to resize the window

### Expected behavior

For the qf window and preview to be side by side, with no gap or overlap.

### Actual behavior

There is either a gap or overlap between the preview window and qf window when resizing.
https://asciinema.org/a/wcLP5UEvnnNolEiQQhH78wEoO

**Comment by kevinhwang91** [comment]
should work after `0.9.2` version.
