### ISSUE TITLE
API to expose "current state"

### ISSUE THREAD

**Issue by iovis** [kevinhwang91/nvim-bqf#127]
### Feature description

Hi!

I wondered if it would make sense to expose something similar to the message we get when we navigate the history of our qf window as something we could query for "status" (to have in a statusline or something like that).

![Screenshot 2023-09-19 at 13 40 55](https://github.com/kevinhwang91/nvim-bqf/assets/6660202/756bb9cd-999c-48a0-8433-4e649421ef5f)

I was looking at [the code](https://github.com/kevinhwang91/nvim-bqf/blob/a906a9dfc1bd7b3ac51ac954e32e157ffad9a7cd/lua/bqf/qfwin/handler.lua#L142-L147C8) and I saw it was done in the moment, so I'm guessing this kind of information about the state may be a bit out of reach at the moment.

### Describe the solution you'd like

I'm open to bounce ideas about what could make sense if you're open to it, but I'm guessing a starting point could be something like `require("bqf").status()` or something to that end

**Comment by kevinhwang91** [comment]
The status of
https://github.com/kevinhwang91/nvim-bqf/blob/8784eebf34371049b641646d00232c2603215297/lua/bqf/qfwin/handler.lua#L142-L147
you can use `vim.fn.getqflist` to get them.

**Comment by iovis** [comment]
Ohhh, for some reason I thought your plugin was keeping state, but I just saw that I can:
```lua
vim.fn.getqflist({ nr = '$' })  -- Get the number of quickfix pages
vim.fn.getqflist({ nr = 0, title = 0 })  -- Get the current page number and title (command)
```

Thank you for clarifying!
