### ISSUE TITLE
not work for tpope/vim-fugitive command   :Gclog -- %

### ISSUE THREAD

**Issue by yimingwangdell** [kevinhwang91/nvim-bqf#128]
### Neovim version (nvim -v | head -n1)

latest

### Operating system/version

manjaro

### How to reproduce the issue

install tpope/vim-fugitive
run :Gclog -- %

### Expected behavior

see previous window works as normal or disable previous window

### Actual behavior

you will see bqf previous window is black.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-bqf/issues/60
