### ISSUE TITLE
Fzf mode emit Command failed

### ISSUE THREAD

**Issue by kevyuu** [kevinhwang91/nvim-bqf#130]
### Neovim version (nvim -v | head -n1)

nvim 0.9.2

### Operating system/version

Windows 11

### How to reproduce the issue

1. Go to fzf mode in quickfix window

Content of bat file: 
@echo off
setlocal enabledelayedexpansion
"fzf"    ^"--color^" ^"gutter:-1^" ^"--scroll-off^" ^"4^" ^"--no-separator^" ^"--multi^" ^"--ansi^" ^"--delimiter^" ^"\^|^" ^"--with-nth^" ^"2..^" ^"--nth^" ^"3..,1,2^" ^"--header-lines^" ^"0^" ^"--tiebreak^" ^"index^" ^"--info^" ^"inline^" ^"--prompt^" ^" Quickfix^> ^" ^"--no-border^" ^"--layout^" ^"reverse-list^" ^"--expect^" ^"ctrl-c,ctrl-q,ctrl-x,ctrl-v,ctrl-t^" ^"--bind^" ^"ctrl-o:toggle-all^" ^"--preview-window^" ^"0^" ^"--preview^" ^"echo {1} ^>^> C:\Users\kevin\AppData\Local\Temp\nvim.0\twEcoJ\0^" --no-height > C:\Users\kevin\AppData\Local\Temp\nvim.0\twEcoJ\1
endlocal

### Expected behavior

Should not emit command failed.

### Actual behavior

![quickfix](https://github.com/kevinhwang91/nvim-bqf/assets/7076807/8a35c7d6-4110-48fa-99e8-979d33003602)

**Comment by kevinhwang91** [comment]
Does fzf.vim work fine for your system?

**Comment by kevyuu** [comment]
:Files seems okay to me
![fzf](https://github.com/kevinhwang91/nvim-bqf/assets/7076807/09ece1b3-732d-48ce-84bf-249ce82995d1)

**Comment by rockyzhang24** [comment]
Maybe it's caused by the parsing, escaping and processing the path in window, which is a nightmare.

**Comment by kevyuu** [comment]
Seems like the issue is in fzf, using list as source for fzf cause problem when using fzf in windows. I have uninstall bqf and try to run fzf#run({'source':['test1', 'test2']}) and get the same error.

**Comment by kevyuu** [comment]
If anyone meet the same issue, can change the $env:shell to cmd.exe. Using powershell as fzf shell seems to be buggy. '^' is an excape character for cmd.exe not powershell

**Comment by rockyzhang24** [comment]
For someone encounting this issue, just throw windows away and switch to using Linux instead!
