### ISSUE TITLE
Respect theme transparency

### ISSUE THREAD

**Issue by SR-MyStar** [kevinhwang91/nvim-bqf#131]
### Feature description

Actually when openning bqf it looks like this:
![图片](https://github.com/kevinhwang91/nvim-bqf/assets/139795416/c284d3b6-335f-4101-ada9-e7fd6f9bdccf)
It doesn't respect my theme transparency and I can't find any solution to make it.

### Describe the solution you'd like

Can we achieve this using a highlight group?

**Comment by rockyzhang24** [comment]
You can freely modify [these bqf's highlight groups](https://github.com/kevinhwang91/nvim-bqf#highlight-groups) according to your preference. You can change the bg of `BqfPreviewFloat` to none to make it transparent.

**Comment by SR-MyStar** [comment]
I already change the bg of BqfPreviewFloat highlight group to none, but now, the background is untransparent too
![图片](https://github.com/kevinhwang91/nvim-bqf/assets/139795416/2a819624-33da-4f17-9a33-b2f4464236fd)

**Comment by rockyzhang24** [comment]
Oh I see. You don't need to modify BqfPreviewFloat. Just set `winblend` to 0 in your bqf config for a fully transparency.

**Comment by SR-MyStar** [comment]
Background is untransparent too
![图片](https://github.com/kevinhwang91/nvim-bqf/assets/139795416/ea6f4cfb-c551-4c5f-8c15-2f14fbaf6658)

**Comment by rockyzhang24** [comment]
As I said, just change `winblend` to 100. Don't change any bqf highlight groups.

**Comment by SR-MyStar** [comment]
Oh, I know, but the background is untransparent after I removed the code for changing bqf's highlight groups too
![图片](https://github.com/kevinhwang91/nvim-bqf/assets/139795416/8c062274-8aa8-450a-822d-d7eb130df47f)

**Comment by rockyzhang24** [comment]
In the pic of your first comment, the bg is already transparent but just kinda opaque. How did you get that?

I mean this pic
<img width="796" alt="image" src="https://github.com/kevinhwang91/nvim-bqf/assets/11582667/0b7a6b34-d6fd-4eb8-a262-ca381c746560">
The words behind bqf are slightly visible.

**Comment by SR-MyStar** [comment]
..., this? It's vim.opt.cursorline
![图片](https://github.com/kevinhwang91/nvim-bqf/assets/139795416/19c6f18d-bca5-4621-bd5d-f66400174196)

**Comment by rockyzhang24** [comment]
No. 
<img width="794" alt="Screenshot 2024-01-12 at 21 19 09" src="https://github.com/kevinhwang91/nvim-bqf/assets/11582667/5a653d82-f398-4f3d-bce3-5c9e41ee1e7a">

**Comment by SR-MyStar** [comment]
![图片](https://github.com/kevinhwang91/nvim-bqf/assets/139795416/c3da5b53-295e-4407-b5e2-76b479feb83e)
Yes, but preview.winblend seems to control the foreground of the text in the BQF preview window. What I want is to remove the solid black background.
![图片](https://github.com/kevinhwang91/nvim-bqf/assets/139795416/722aaed7-65eb-402c-ae74-fd3ef2340ddc)

**Comment by rockyzhang24** [comment]
:h winblend

**Comment by SR-MyStar** [comment]
Please take a look at this image. It shows the effect of winblend = 100.
![图片](https://github.com/kevinhwang91/nvim-bqf/assets/139795416/1ada5672-0a56-41fa-8631-299d395c00be)
So, it seems like winblend is unrelated to this issue.

**Comment by rockyzhang24** [comment]
cannot help. good luck.

**Comment by kevinhwang91** [comment]
winblend=0

**Comment by SR-MyStar** [comment]
Emm, use it
```lua
return {
  "kevinhwang91/nvim-bqf",
  ft = "qf",
  lazy = true,
  opts = {
    preview = {
      winblend = 0,
    },
  },
}
```
![图片](https://github.com/kevinhwang91/nvim-bqf/assets/139795416/52e91cce-fd6f-4b8b-8e31-394fef88a910)
