### ISSUE TITLE
bqf causing nvim to exit

### ISSUE THREAD

**Issue by swtch1** [kevinhwang91/nvim-bqf#133]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.5

### Operating system/version

macOS 14.2.1

### How to reproduce the issue

Unfortunately this issue has been difficult for me to reproduce, but these were my actions during the most recent crash:

1. load a large number of items into bqf
2. scroll up and down as fast as possible

This does not always reproduce the issue, and I've had it happen in other actions like just pressing enter to navigate to an item, but it is not consistent.

To capture debugging information I ran `nvim -V9vim.log` until I was able to capture the crash, which happened after a very long session.  Unfortunately I'm not able to glean the root issue from the log but I've included the last part of it for analysis. 

[vim.log](https://github.com/kevinhwang91/nvim-bqf/files/14087505/vim.log)

This is absolutely one of my favorite plugins so I would love to find the issue here.

### Expected behavior

I expect bqf to run without ever causing nvim to exit.

### Actual behavior

Using bqf causes nvim to exit.

**Comment by swtch1** [comment]
After some extra research and reviewing the logs again I believe this issue may be caused by vim-gitgutter rather than this plugin.  I'm doing some extra checks and will close this issue if I can confirm.

**Comment by rockyzhang24** [comment]
Use gitsigns.nvim instead.
