### ISSUE TITLE
Creating a new tab causes `<CR>` mapping to break

### ISSUE THREAD

**Issue by ColinKennedy** [kevinhwang91/nvim-bqf#134]
### Neovim version (nvim -v | head -n1)

v0.9.4

### Operating system/version

CentOS Linux 7 (Core)

### How to reproduce the issue

<details>
<summary>Show reproduction.lua file</summary>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"

if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end

vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    -- Quickfix auto previews and other fun features
    {
        "kevinhwang91/nvim-bqf",
        dependencies = {"junegunn/fzf", "nvim-treesitter/nvim-treesitter"},
        ft = "qf",
        version = "0.*",
    },
}

require("lazy").setup(plugins, { root = root .. "/plugins" })
```
</details>

1. Have 2+ files to search within (I use a clone of Neovim in my example video)
2. Load `nvim` with the reproduction file above

3. Call `:vimgrep` to populate the quickfix
4. Call `:copen` and press `<CR>` on one of the quickfix window's entries
5. Call `:tabedit %`
6. Call another `:vimgrep` to re-populate the quickfix
7. Call `:copen` in this new tab and press `<CR>` on one of the quickfix window's entries
8. Call `:tabprevious` to go to the previous tab
9. Focus the previous tab's quickfix window and press `<CR>` on just about any entry. It will not go to the correct file or line number

### Expected behavior

<CR> should go to the selected index's file + line number regardless of which tab you are currently in.

### Actual behavior

An incorrect file / line number is selected. And it seems to be permanently off until the tabs are deleted or Neovim is restarted.

https://github.com/kevinhwang91/nvim-bqf/assets/10103049/df1187b1-b5bb-47af-97e1-d14dbda59150

**Comment by ColinKennedy** [comment]
Wow, that was fast. Thank you!!

**Comment by ColinKennedy** [comment]
Tested, works great. @kevinhwang91 any chance we can get a new git tag for nvim-bqf? The last git tag (and git release) is almost a year old to the day. Thank you again for this wonderful plugin!

**Comment by kevinhwang91** [comment]
> Tested, works great. @kevinhwang91 any chance we can get a new git tag for nvim-bqf? The last git tag (and git release) is almost a year old to the day. Thank you again for this wonderful plugin!

Done.
