### ISSUE TITLE
Disable automatic preview mode warning

### ISSUE THREAD

**Issue by xquilt** [kevinhwang91/nvim-bqf#137]
### Neovim version (nvim -v | head -n1)

NVIM v0.9.5

### Operating system/version

Elementary OS 5.1 Horus

### How to reproduce the issue

1. Toggle the automatic preview mode
2. Get an obtrusive warning
3. have to skip the warning each time it's toggled on and off

### Expected behavior

The mode is toggled silently or at the very least get notified in a non-obtrusive manner (provide a call-back to define that behavior even)

### Actual behavior

Got a [warning](https://github.com/kevinhwang91/nvim-bqf/blob/52703d7adc3be3f7c09eea9a80c5b8caa615fb25/lua/bqf/preview/handler.lua#L354) whenever automatic preview mode is toggled

**Comment by kevinhwang91** [comment]
You can disable auto preview and type `p` to toggle it manually.

**Comment by xquilt** [comment]
I would like to still use auto previews but without this somewhat nagging warning.

**Comment by kevinhwang91** [comment]
I will show the msg at the bottom except your `ch` is equal to 0. And I don't think your attention will be at the bottom if you are focusing on the preview window.

**Comment by xquilt** [comment]
>  I don't think your attention will be at the bottom if you are focusing on the preview window.

It does show up at the bottom, but I'd have to press Enter every time I toggle auto preview on and off. 
>  bottom except your ch is equal to 0.

Sorry. I'm not following

**Comment by kevinhwang91** [comment]
> but I'd have to press Enter every time I toggle auto preview on and off.

No need to type any keys for me, it's an issue with your config.

**Comment by xquilt** [comment]
That's the current behavior

![Screenshot from 2024-05-03 12 51 07](https://github.com/kevinhwang91/nvim-bqf/assets/48662854/cb1b2b97-e2a9-4fbe-8cb0-ebb0944296b0)

**Comment by kevinhwang91** [comment]
`h 'shortmess'`
