### ISSUE TITLE
Cannot make :copen work, still shows the normal one

### ISSUE THREAD

**Issue by lucax88x** [kevinhwang91/nvim-bqf#14]
- NVIM v0.5.0-dev+1274-gbb3372792
- archlinux

**Describe the bug**
when I do :copen I still see the old one

**To Reproduce using `nvim -u mini.vim`**

I cannot test using your mini.vim, it gives some error :O

<img width="549" alt="2021-04-24_21-58" src="https://user-images.githubusercontent.com/6294464/115971369-5491c600-a548-11eb-9a27-22695e0dfea0.png">

1. :copen

**Expected behavior**
I expect to see the floating window with list of quickfixes, but I still see the default one

**Screenshots**
<img width="960" alt="2021-04-24_22-00" src="https://user-images.githubusercontent.com/6294464/115971378-64110f00-a548-11eb-9753-90f101232a6d.png">

**Additional context**
I am sure it's something wrong on my side, I just don't know where..

[this is my dotfiles](https://github.com/lucax88x/configs/blob/master/dotfiles/.config/nvim/lua/lt/plugins.lua#L49)

**Comment by kevinhwang91** [comment]
Look like a git log produced by the fugitive. These items are always `lnum = 0` and `col = 0`. Let me consider how to preview them properly.

**Comment by lucax88x** [comment]
So I got  weird case? How can I just open your window? I wanted to see the difference with my eyes

**Comment by kevinhwang91** [comment]
`vim /pattern/gj %`

**Comment by kevinhwang91** [comment]
Feel free to ask any question here, but allow me to close the issue.
