### ISSUE TITLE
incorrectly enter insert mode

### ISSUE THREAD

**Issue by yimingwangdell** [kevinhwang91/nvim-bqf#141]
### Neovim version (nvim -v | head -n1)

any

### Operating system/version

any

### How to reproduce the issue

1.open a quickfix list
2.open with  \<CR\>
3. \<c-w\>\<down\> back to list
4. open with "o"
5. windows opened but enter insert mode.

### Expected behavior

do not enter insert mode after open with "o"

### Actual behavior

windows opened but enter insert mode.

**Comment by yimingwangdell** [comment]
@kevinhwang91

**Comment by kevinhwang91** [comment]
can't reproduce it.

**Comment by yimingwangdell** [comment]
https://github.com/yimingwangdell/vimrc/blob/master/nvim/init.vim
