### ISSUE TITLE
How to setup keymaps to avoid conflict with folding

### ISSUE THREAD

**Issue by aimestereo** [kevinhwang91/nvim-bqf#142]
### Feature description

bqf keymaps are heavily conflicting with folding
![Screenshot 2024-05-19 at 11 26 22](https://github.com/kevinhwang91/nvim-bqf/assets/2869535/3f55b3ef-d1f6-49ed-8042-50447c195433)

### Describe the solution you'd like

Please explain how to configure bqf or qf list, so that either
* folding keymaps are disabled for qf list
* bqf keymaps takes priority

### Additional context

I was using bqf for a year now, just as a replacement for qf list. Now I've tried to use more its features and become confused, maybe I'm doing smth wrong.

my current approach:
* remap z* to smth else `zf`:`ff`, `zo`: z0`
* additional `ctrl-o` works great, thanks
* `zn`, `zN`, `zp`, `zP` works out of the box

```lua
return {
  {
    "kevinhwang91/nvim-bqf",
    ft = "qf",
    event = "VeryLazy",
    config = function()
      ...

      -- Make Neovim's quickfix window better: preview, fzf, actions.
      require("bqf").setup({
        ...

        func_map = {
          fzffilter = "ff",    -- default: "zf"
          pscrollorig = "z0",  -- default: "zo"
        },

        filter = {
          fzf = {
            extra_opts = { "--bind", "ctrl-o:toggle-all", "--delimiter", "│" },
          },
        },
      })
    end,
  },
}
```

**Comment by kevinhwang91** [comment]
```lua
  func_map = {
          fzffilter = '',
          pscrollorig = ''
        },
```
