### ISSUE TITLE
How do I use `:cdo` with selected item in quickfix window

### ISSUE THREAD

**Issue by amikai** [kevinhwang91/nvim-bqf#147]
### Feature description

Occasionally, I want to use the `cdo` command with nvim-bqf selected items. How can I achieve this ?

### Describe the solution you'd like

Maybe use the `:args` to bridge
1. Send nvim-bqf selected item to argument list (Maybe there is an easy way to do this, but I don't know)
2. Use `:argdo` with argument list

**Comment by kevinhwang91** [comment]
`h cdo`

You should filter out selected items and exe `cdo`. bqf can type `zn` and `zN` to implement that or enter fzf mode to filter them.
