### ISSUE TITLE
BqfPreviewScrollBar sometimes saved

### ISSUE THREAD

**Issue by propri** [kevinhwang91/nvim-bqf#148]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0

### Operating system/version

Linux Mint 21.3

### How to reproduce the issue

Sometimes writing all buffers with :wa saves a new file BqfPreviewScrollBar. Not always, and I cannot reliably reproduce this behavior.

1. Save all buffers with :wa

### Expected behavior

BqfPreviewScrollBar not saved to disk

### Actual behavior

BqfPreviewScrollBar saved to disk

**Comment by kevinhwang91** [comment]
Some plugins change the `buftype` for BqfPreviewScrollBar.
