### ISSUE TITLE
Let me reconfigure the setup

### ISSUE THREAD

**Issue by yutkat** [kevinhwang91/nvim-bqf#15]
- `nvim --version`:　v0.5.0-dev+1272-g4570d04b1
- Operating system/version: ArchLinux

**Describe the bug**
I am using nvim-bqf with packer's lazy loading feature. But in that state, I cannot change the mapping because it is caught by the following reload prevention.
https://github.com/kevinhwang91/nvim-bqf/blob/7c750a7398797522934d401ffc3ead4a45e8fca1/lua/bqf.lua#L7-L9

I would like to be able to change the mapping even for lazy loading.

**To Reproduce using `nvim -u mini.vim`**

Example:
`cat mini.vim`

```vim
syntax enable
filetype plugin indent on

lua <<EOF
local execute = vim.api.nvim_command
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/opt/packer.nvim'

if fn.empty(fn.glob(install_path)) > 0 then
  execute('!git clone https://github.com/wbthomason/packer.nvim '..install_path)
end

vim.cmd [[packadd packer.nvim]]
return require('packer').startup(function()
  use {'wbthomason/packer.nvim', opt = true}
  use {'kevinhwang91/nvim-bqf', opt = true,
    event = 'VimEnter',
    config = function() require('bqf').setup({func_map = { pscrollup = '<C-u>', pscrolldown = '<C-d>'}}) end
  }
  use {'junegunn/fzf',
    run="call fzf#install()",
  }
end)
EOF
```

1. `:copen`
2. `:nmap <buffer> <C-f>`
3. `:nmap <buffer> <C-u>`

**Expected behavior**
I'd like to be able to change the mapping even if I use a lazy load.

**Comment by kevinhwang91** [comment]
Do you know the startup time of bqf is so fast compared with other lua plugins?
I don't understand why use `VimEnter` to load bqf. `setup({})` never validates user data and deepcopy config table.
bqf will defer do these function.

**Comment by yutkat** [comment]
I know it's fast.

But I just want to use as much lazy loading as possible to control. (VimEnter is just an example)
However, I understood that this program was created with a policy of no lazy loading.

Thank you for your support :+1:

**Comment by kevinhwang91** [comment]
I will fix it latter. Sometimes I hate the plugin locate in start/ path

**Comment by yutkat** [comment]
Thank you for your great work!
