### ISSUE TITLE
Question: jump to next item in quickfix, when focused main buffer

### ISSUE THREAD

**Issue by rusnasonov** [kevinhwang91/nvim-bqf#152]
### Feature description

Is the way to iterate over quickfix items, when cursor focused on main buffer (not quickfix buffer)?

I want to search files by pattern, and switch fast between found items. Like `n` and `b` keys in local search `/`. 

### Describe the solution you'd like

-

**Comment by kevinhwang91** [comment]
`cnf` and `cpf`
