### ISSUE TITLE
Update README about drop and creating a new quicklist from the result of fzf

### ISSUE THREAD

**Issue by srgsanky** [kevinhwang91/nvim-bqf#153]
### Feature description

Two things are not clear to me from the README. Can you clarify these?

> drop | use drop to open the item, and close quickfix window | O

1. What is drop? Is it supposed to delete the item from the quickfix list? I don't see a difference in behavior between o and O.
2. If I filter the list using fzf (using `zf`), how can I create a new list from only the filtered items?

---
PS: Wonderful plugin! I discovered this from https://www.youtube.com/watch?v=W4aLqTV4qkc&t=771s

### Describe the solution you'd like

Please update the README with these details - may be in FAQ. Others might have the same question.

**Comment by srgsanky** [comment]
> If I filter the list using fzf (using zf), how can I create a new list from only the filtered items?

I figured out how to do this when fzf has multiple search results - I just have to press `Tab` to move to the search results, use `<C-n>` or `<C-p>` to navigate around the list, use `Tab` to toggle selection of the current item and hit `Enter` to create a new list with the selection. Neat!

I was initially playing around with a search that returns only one result. The above approach was is working in this case. This behavior is reasonable when there is only one search result, but is not consistent. When I reopen the quickfix list with `:copen`, I see all the items again.

**Comment by kevinhwang91** [comment]
> What is drop? Is it supposed to delete the item from the quickfix list? I don't see a difference in behavior between o and O.

You can find the answer from `: drop`.

> I was initially playing around with a search that returns only one result. The above approach was is working in this case. This behavior is reasonable when there is only one search result, but is not consistent. When I reopen the quickfix list with :copen, I see all the items again.

fzf can't record selected item when doing handler. If you want to keep only selected item, please type `ctrl-q` to sign it back to the qf list, and then type `zn` to create new qf list.

**Comment by srgsanky** [comment]
Thanks for these pointers!

> You can find the answer from : drop.

I read https://neovim.io/doc/user/windows.html#_the-argument-list-and-multiple-windows on `:drop`

> [:dr](https://neovim.io/doc/user/windows.html#%3Adr) [:drop](https://neovim.io/doc/user/windows.html#%3Adrop)
:dr[op] [++opt] [+cmd] {file} ..
		Edit the first {file} in a window.
If the file is already open in a window change to that window.
If the file is not open in a window edit the file in the current window. If the current buffer can't be [abandon](https://neovim.io/doc/user/editing.html#abandon)ed, the window is split first.
Windows that are not in the argument list or are not full width will be closed if possible. The [argument-list](https://neovim.io/doc/user/editing.html#argument-list) is set, like with the [:next](https://neovim.io/doc/user/editing.html#%3Anext) command. The purpose of this command is that it can be used from a program that wants Vim to edit another file, e.g., a debugger. When using the [:tab](https://neovim.io/doc/user/tabpage.html#%3Atab) modifier each argument is opened in a tab page. The last window is used if it's empty. Also see [++opt](https://neovim.io/doc/user/editing.html#%2B%2Bopt) and [+cmd](https://neovim.io/doc/user/editing.html#%2Bcmd).

If I use `O` on a file that is not currently open, it is not reusing the current buffer (the current buffer is clean and not dirty). It is always opening in a new buffer. I still don't understand the difference between `o` and `O`. Either I am misunderstanding the behavior or something in my config is interfering with this behavior.

> fzf can't record toggled items but returns the select indexes directly when doing the handler. If you want to keep only the toggled item, please type ctrl-q to sign it back to the qf list, and then type zn to create a new qf list.

This works 👍

**Comment by kevinhwang91** [comment]
Open two buffers a and b, switch to b buffer and then run `:drop path_of_a`.

**Comment by srgsanky** [comment]
> The purpose of :drop is to prevent opening the same file in multiple buffers and windows, ensuring that if the file is already loaded, you simply switch to it, rather than loading it again.

Something in my configuration is already preventing opening of duplicate buffers so I am not able to see the benefit of `O` over `o`. The behavior is the same for me.

Thanks for patiently explaining about `:drop`. Today I learnt yet another new command!
