### ISSUE TITLE
Preview window does not close when FZF is opened

### ISSUE THREAD

**Issue by jearbear** [kevinhwang91/nvim-bqf#154]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0

### Operating system/version

macOS 13.5.1

### How to reproduce the issue

1. Have quickfix open with preview window open
2. Open FZF
3. FZF window will be opened below the preview window
...

<img width="746" alt="image" src="https://github.com/user-attachments/assets/1a6a0323-a15f-45ac-bead-418037c6a4be">

### Expected behavior

I would expect the preview window to be closed as would be the case if I switched to a different buffer. I tried working around this in a few ways:

1. Updating my mappings that open FZF to do `require("bqf").hidePreviewWindow()` first. This seems to have no effect.
2. Adding a `BufLeave` autocmd for the quickfix buffer to call `require("bqf").hidePreviewWindow()`. This also seems to have no effect.

I'm wondering if part of the issue is that `hidePreviewWindow` only takes effect if the quickfix is currently focused?

### Actual behavior

FZF window will be opened below the preview window.

**Comment by kevinhwang91** [comment]
I can't reproduce it. Could you make your config minimized?

**Comment by jearbear** [comment]
Sorry, I should have clarified that I'm referring to the [fzf-lua](https://github.com/ibhagwan/fzf-lua) plugin that uses a floating window. I assumed it was an issue with all floating windows, but I couldn't reproduce this by calling `vim.api.nvim_open_win`. The issue only occurs when calling `FzfLua`. I'll dig in more tonight and try to better understand the issue.

**Comment by kevinhwang91** [comment]
fzf-lua issue.
https://github.com/ibhagwan/fzf-lua/blob/ce1e24f2a48089b65deefcb0a71a9856839002b5/lua/fzf-lua/utils.lua#L1042-L1044

https://github.com/kevinhwang91/nvim-bqf/blob/1b24dc6050c34e8cd377b6b4cd6abe40509e0187/lua/bqf/preview/handler.lua#L469
