### ISSUE TITLE
exception when call :lua vim.lsp.buf.reference() 2nd time

### ISSUE THREAD

**Issue by echoface** [kevinhwang91/nvim-bqf#155]
### Neovim version (nvim -v | head -n1)

NVIM 0.10.1

### Operating system/version

macOS 15

### How to reproduce the issue

1. config  gopls by nvim-lspconfig 
2. call :lua vim.lsp.buf.reference() 
3. everything working well
4. :cclose
5. call :lua vim.lsp.buf.reference() agin ; throw exception error here;

https://github.com/user-attachments/assets/4ed770d1-4cea-468b-bfcf-8aa22eb57a6b

### Expected behavior

just work

### Actual behavior

```
Error executing vim.schedule lua callback: BufReadPost 自动命令 "*": Vim(lua):E5108: Error executing lua ...local/share/nvim/lazy/nvim-bqf/lua/b
qf/qfwin/handler.lua:111: attempt to index local 'qs' (a nil value)
stack traceback:
        ...local/share/nvim/lazy/nvim-bqf/lua/bqf/qfwin/handler.lua:111: in function 'restoreWinView'
        [string ":lua"]:1: in main chunk
        [C]: in function 'setqflist'
        ...eovim/0.10.1/share/nvim/runtime/lua/vim/lsp/handlers.lua:264: in function 'handler'
        .../neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'setqflist'
        ...eovim/0.10.1/share/nvim/runtime/lua/vim/lsp/handlers.lua:264: in function 'handler'
        .../neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by kevinhwang91** [comment]
I can't reproduce it, check out your other plugins that may cause this issue.

**Comment by echoface** [comment]
got it，confirm that the issue caused by a autocmd,thanks 👍

Kevin Hwang ***@***.***> 于 2024年12月15日周日 16:20写道：
