### ISSUE TITLE
remove selected qf element

### ISSUE THREAD

**Issue by JoseConseco** [kevinhwang91/nvim-bqf#16]
**Is your feature request related to a problem? Please describe.**
Remove selected QF entry - with dd (or other key)

**Describe the solution you'd like**
Here is code that should work. I wish this was build-in function in bqf - so we could easily remove selected elements 
https://stackoverflow.com/a/48817071/13588868

**Comment by kevinhwang91** [comment]
Use `<tab>` to sign the single or multiple items, and then press `zN`. I think this filter way is better than the link you provide.

BTW, You can remap `zN` to `dd`.

**Comment by thekaganugur** [comment]
Hi,
I tried `zN` and `lua require('bqf.filter.base').run(true)` and nothing seems to happen.

**Comment by kevinhwang91** [comment]
> Hi, I tried `zN` and `lua require('bqf.filter.base').run(true)` and nothing seems to happen.

No idea why, but work for me. Open a new issue with mini.lua
