### ISSUE TITLE
When there is no float window, excuting "bd"  will report an error.

### ISSUE THREAD

**Issue by cogig** [kevinhwang91/nvim-bqf#17]
- `nvim --version`:NVIM v0.5.0-dev+1282-gfbe18d9ca
- Operating system/version:ubuntu 20.04

**Describe the bug**

Vim(quit):E5601: Cannot cl ose window, only floating window would remain

**Comment by kevinhwang91** [comment]
More information, please.

**Comment by cogig** [comment]
Error detected while processing CursorMoved Autocommands for "<buffer=24>":                                     
E5108: Error executing lua /home/cogig/.nvim/plugged/nvim-bqf/lua/bqf/qftool.lua:15: Vim(quit):E5601: Cannot cl
ose window, only floating window would remain

**Comment by kevinhwang91** [comment]
How can I reproduce this issue?

**Comment by cogig** [comment]
When using nvim-bqf, move the cursor of quickfix to another window, at this time the float window of nvim-bqf will disappear, then execute the "bd" command, you will see this error.

**Comment by kevinhwang91** [comment]
You'd better try a minimal configuration. The error said your current tabpage has another floating window.

**Comment by cogig** [comment]
My config followed LunarVim? I don't know how to troubleshoot this error. Maybe I should close this issue. Thank you for your reply.

**Comment by kevinhwang91** [comment]
Never mind, feel free to reopen it when you care about it.
