### ISSUE TITLE
Support to visual select till next or previous file

### ISSUE THREAD

**Issue by zlksnk** [kevinhwang91/nvim-bqf#20]
I believe currently there is no way to select all matches of a file. This is useful to exclude files in new list that is created out from it by marking all matches of those files.

**Solution proposal**
1. Leverage existing `<tab>` implementation with `<c-n>` and `<c-p>` — for visual mode, add `<c-n>` and `<c-p>` keybindings that behave slightly different from their normal mode counterparts; or 
1. Add shortcuts for normal mode —  `z<tab>` and `z<s-tab>` (preferable, otherwise `zm` and `zM`) to toggle all matches of file and go to next or previous file respectively.

I prefer point 2.

**Alternatives I considered**
I wasn't able to find a good enough alternative for this.

**Additional context**
romainl/vim-qf provides a command to act on occurrences in a file.

**Comment by kevinhwang91** [comment]
I'm thinking about how to implement it.

**Comment by kevinhwang91** [comment]
`'<Tab>` will toggle the same buffers under the cursor.  Because the qf list may not be sorted, we can't navigate up or down, so stand in place but adding signs is a good idea.

If you dislike `'<Tab>zn` or `'<Tab>zN`, you can feel free to remap your own key.
