### ISSUE TITLE
Unexpectedly set number

### ISSUE THREAD

**Issue by zdmgmail** [kevinhwang91/nvim-bqf#23]
- `nvim --version`:
    NVIM v0.5.0-dev+1298-g4ad30f775
- `Operating system/version:`
    Linux 5.11.16-arch1-1

**Describe the bug**

I use `set nonumber` in init.vim

use `vimgrep /\w\+/j % | copen` work ok

but use this plug(about quickfix)  [ack.vim](https://github.com/mileszs/ack.vim) , `:Ack pattern` open a quickfix, then enter file, new file will auto `set number`

if not use `nvim-bqf`, not auto set number

**To Reproduce using `nvim -u mini.vim`**

```vim
call plug#begin('~/.config/nvim/plugged')
        Plug 'kevinhwang91/nvim-bqf'
        Plug 'mileszs/ack.vim'
call  plug#end()

set nonumber
```

**Comment by zdmgmail** [comment]
@kevinhwang91  this problem fix success? I update but still have this problem?

**Comment by kevinhwang91** [comment]
Yes, at less in rg. I don't use ag or ack.

You'd clean up your env and provide a screenshot or record here.

**Comment by zdmgmail** [comment]
@kevinhwang91  well ... `rg` or `ag` not get problem ,  just happen when I use  [ack.vim](https://github.com/mileszs/ack.vim)

**Comment by kevinhwang91** [comment]
You may check the doc of ack.vim. The new window options will follow the last window opened.
I reset the options of file win for the new window in https://github.com/kevinhwang91/nvim-bqf/commit/24d63bc31b0d19a5bb4f219bf58a57bd84e1ec74

**Comment by zdmgmail** [comment]
@kevinhwang91 

the problem is the last window(quickfix) auto set number, don't need `ack.vim`, just use `vimgrep /\w\+/j **/* | copen 
` search dir and open a different file will get same problem

**Comment by kevinhwang91** [comment]
It can reproduce before https://github.com/kevinhwang91/nvim-bqf/commit/24d63bc31b0d19a5bb4f219bf58a57bd84e1ec74. https://github.com/kevinhwang91/nvim-bqf/commit/24d63bc31b0d19a5bb4f219bf58a57bd84e1ec74 actually has fixed this issue.
Again, clean up your env.

**Comment by zdmgmail** [comment]
@kevinhwang91 , sorry... after clean, it caused by this plug [https://github.com/gcmt/wildfire.vim](wildfire.vim)  , it's a text object plugin,  don't know why ...

new config, and use `vimgrep /\w\+/j **/* | copen`

```
call plug#begin('~/.config/nvim/plugged')
        Plug 'kevinhwang91/nvim-bqf'                              " preview quickfix
        Plug 'gcmt/wildfire.vim'
call  plug#end()

set nonumber
```

**Comment by kevinhwang91** [comment]
`map <CR>` in quickfix window you will know what it does.
https://github.com/gcmt/wildfire.vim/blob/e2baded7162260e05d2527f5bca9fca81f0bc8f2/plugin/wildfire.vim#L69-L76

**Comment by zdmgmail** [comment]
@kevinhwang91  thanks , solved
