### ISSUE TITLE
Sometimes the preview window does not close

### ISSUE THREAD

**Issue by tamago324** [kevinhwang91/nvim-bqf#24]
- `nvim --version`: `NVIM v0.5.0-dev+1293-ga0da4c3a4`
- Operating system/version: Manjaro

**Describe the bug**

Preview window does not close when it loses focus after opening a new window in `:new`.

**To Reproduce using `nvim -u mini.vim`**

```vim
set encoding=utf-8

filetype plugin indent on
if has('vim_starting')
  let s:pluin_manager_dir='~/.config/nvim/.plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif
call plug#begin('~/.config/nvim/.plugged')
Plug 'kevinhwang91/nvim-bqf'
call plug#end()

set nobackup
set nowritebackup
set noswapfile
set updatecount=0
set backspace=indent,eol,start
language messages en_US.utf8

lua << EOF

require'bqf'.setup{
  preview = {
    win_height = 10
  }
}

EOF
```

1. `nvim -u mini.vim -i NONE ./sample.vim`
  sample.vim
    ```
    hello world

    hello
    ```

2. `:vimgrep /hello/ %:p | cwindow` (open quickfix window)
3. `:new`
4. `:cclose`
5. The preview window stays open.

**Expected behavior**
Close the preview window when a new window is opened in `:new`.

**Screenshots**

https://user-images.githubusercontent.com/16581287/118120765-5c4bd880-b42b-11eb-8082-e6357fd529c6.mp4

Thank you!

**Comment by kevinhwang91** [comment]
Nice record! I can reproduce the issue easily ~ I will take a look later.

**Comment by kevinhwang91** [comment]
Fixed :)

**Comment by tamago324** [comment]
Thank you!!

**Comment by kevinhwang91** [comment]
From your record and my experience, I found the essential issue is leaving qf window can't stop the preview. I have pushed the patch to the repo. Now, after `new`, the preview window will be closed at once.

**Comment by tamago324** [comment]
It's perfect! Thank you!
