### ISSUE TITLE
Add default mapping to delete an entry from the quickfix list

### ISSUE THREAD

**Issue by rmagatti** [kevinhwang91/nvim-bqf#27]
> Is your feature request related to a problem? Please describe.  

No problem, just convenience.

> Describe the solution you'd like

A default mapping of, for example, `dd` to delete an entry in the quickfix list would be awesome.

> Describe alternatives you've considered

Well you can do this manually
https://www.reddit.com/r/vim/comments/7dv9as/how_to_edit_the_vim_quickfix_list/

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-bqf/issues/16

After remapping `dd` to `zN`,  `<tab>` the items you want to delete and press `dd` will get what you expect. 
Bqf only supports to use of signs to filter items, there's no concept of deletion directly.
Assume Bqf supports the delete method, other guys open an issue for `redo`, how can we implement this easily? That's the limit of native qf.

Bqf almost compatible with other qf plugins. If you like the more like vim way `dd`, you can use other plugins or write your own script to implement it.

**Comment by rmagatti** [comment]
Oh that's my bad I didn't find #16 in my search 🤦 .

Yeah I think that's actually fine. A simple `dd` to delete the currently selected entry would be nice but I think I can adjust to the way you described.

Either that or I'll cook something up so the mapping does what I want, either way thanks for the swift reply. I'll close this now and might update the thread if I end up doing anything custom for this.

**Comment by kevinhwang91** [comment]
Thanks for your understanding. Any feedback is welcome.
