### ISSUE TITLE
[Feature Request] Support syntax highlighting and align for fzf

### ISSUE THREAD

**Issue by kevinhwang91** [kevinhwang91/nvim-bqf#28]
`quickfixtextfunc` is ported to upstream master, `:h qftf` for detail.

![image](https://user-images.githubusercontent.com/17562139/119068441-c6114700-ba16-11eb-92bb-8c40796c1142.png)
![image](https://user-images.githubusercontent.com/17562139/119068456-cc072800-ba16-11eb-9754-67b4f5161160.png)

How can we let users easily customize fzf within nvim-bqf?

**Comment by kevinhwang91** [comment]
BTW, if the valid = 0 of the item, how to handle it? Padding or truncating? :(

**Comment by akinsho** [comment]
@kevinhwang91 👋🏾 , will the alignment you show in the first screenshot only apply to fzf? if so why?

can any quickfix list now be aligned if this plugin sets a `quickfixtextfunc` which checks the longest item in each column and uses that to determine the width so they are all aligned?

**Comment by kevinhwang91** [comment]
@akinsho 

The first screenshot is set `quickfixtextfunc` to customize the quickfix. `:h qftf` fot details. No matter `nvim-bqf` is used or not, you can get the alignment like the first screenshot.
Here is my global config about qftf:
```lua
function _G.qftf(info)
    local items
    local ret = {}
    if info.quickfix == 1 then
        items = fn.getqflist({id = info.id, items = 0}).items
    else
        items = fn.getloclist(info.winid, {id = info.id, items = 0}).items
    end
    local limit = 25
    local fname_fmt1, fname_fmt2 = '%-' .. limit .. 's', '…%.' .. (limit - 1) .. 's'
    local valid_fmt, unvalid_fmt = '%s |%5d:%-3d|%s %s', '%s'
    for i = info.start_idx, info.end_idx do
        local e = items[i]
        local fname = ''
        local str
        if e.valid == 1 then
            if e.bufnr > 0 then
                fname = fn.bufname(e.bufnr)
                if fname == '' then
                    fname = '[No Name]'
                else
                    fname = fname:gsub('^' .. vim.env.HOME, '~')
                end
                if fn.strwidth(fname) <= limit then
                    fname = fname_fmt1:format(fname)
                else
                    fname = fname_fmt2:format(fname:sub(1 - limit, -1))
                end
            end
            local lnum = e.lnum > 99999 and 'inf' or e.lnum
            local col = e.col > 999 and 'inf' or e.col
            local qtype = e.type == '' and '' or ' ' .. e.type:sub(1, 1):upper()
            str = valid_fmt:format(fname, lnum, col, qtype, e.text)
        else
            str = unvalid_fmt:format(e.text)
        end
        table.insert(ret, str)
    end
    return ret
end

vim.o.qftf = 'v:lua._G.qftf'
```
The issue is for fzf mode.
For now, fzf mode just mock the style of the native format, the second is fzf mode although I had set the `quickfixtextfunc`.

We can use extmarks to render the quickfix list instead of syntax pattern, and then get the extmarks to render fzf mode.
But this method will cause a performance issue. Syntax pattern is simple and is faster than extmarks.
So I don't know how to make fzf mode respect both highlighting and alignment if `quickfixtextfunc` is set.

**Comment by akinsho** [comment]
@kevinhwang91 thanks for clarifying and for the snippet, I completely misunderstood what this issue was about. I thought it included adding a qftf by default but only if using fzf 🤦🏾‍♂️.

**Comment by kevinhwang91** [comment]
Yes, if don't use fzf, feel free to customize your qf by `qftf`. I will make fzf work well recently.
