### ISSUE TITLE
Set number for pages

### ISSUE THREAD

**Issue by timsofteng** [kevinhwang91/nvim-bqf#29]
Hello. I'm not using `set numbers` opriton for my nvim windows but `nvim-bqf` enables it. How can i disable this option for all windows except quick-fix list?

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-bqf/blob/3754935f6c6b9eaae203fe9d4620e2d3e1a8f0ef/lua/bqf/main.lua#L48-L50
`au FileType qf lua vim.schedule(function() vim.wo.number = false end)` is a workaround.
For now, I don't want to expose the qf callback, I need a compelling reason.
