### ISSUE TITLE
Wrap lines in preview

### ISSUE THREAD

**Issue by jupblb** [kevinhwang91/nvim-bqf#31]
**Is your feature request related to a problem? Please describe.**
I wish there was a way to enable line soft wrap in the preview buffer.

**Describe the solution you'd like**
A config that allows me to enable line soft wrap. Could be `preview.soft_wrap`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kevinhwang91** [comment]
I have waited for this request for a long time :)
The option is coming.

**Comment by jupblb** [comment]
Wow. :D I'm speechless about how fast you helped me. :) Thanks!

**Comment by nachovizzo** [comment]
Is there any example config?

```
require 'bqf'.setup({
    wrap = true,
})
```

Doesn't work for me

**Comment by rockyzhang24** [comment]
Well, it is already mentioned in README. See https://github.com/kevinhwang91/nvim-bqf#setup-and-description

**Comment by nachovizzo** [comment]
@rockyzhang24 that's where I took it from. But has no effect. I'm not experienced with lua at all. I end up modifying locally the plugin to fix it, but it's not ideal of course

**Comment by rockyzhang24** [comment]
```lua
require 'bqf'.setup({
    preview = {
        wrap = true,
    }
})
```

**Comment by nachovizzo** [comment]
@rockyzhang24 Thanks! that worked
