### ISSUE TITLE
[FR] Option to disable preview window only for some file types

### ISSUE THREAD

**Issue by jaekyeom** [kevinhwang91/nvim-bqf#33]
**Is your feature request related to a problem? Please describe.**
Sometimes, I grep over PDF files (using [rga](https://github.com/phiresky/ripgrep-all)) and list them in the quickfix window just to load them into a vim buffer.
nvim-bqf opens the preview window for the PDF files, which is lagging and not very helpful.

**Describe the solution you'd like**
I wish there is an option to list file types or file extensions for which nvim-bqf does not show the preview window.

**Describe alternatives you've considered**
I currently call `:BqfDisable` manually, but even opening the preview window for the first item in the quickfix window is slow.
I wouldn't set `auto_preview` or `auto_enable` to false since I find this plugin really useful in general.

**Comment by kevinhwang91** [comment]
Make sense. I will add an option for this request.

**Comment by kevinhwang91** [comment]
It's hard to detect filetype within a few ms, which may cause laging.  So add a callback function with a bufnr is a better solutioin.
You can try below configuration:
```lua
    require('bqf').setup({
        auto_enable = true,
        preview = {
            auto_preview = true,
            should_preview_cb = function(bufnr)
                local ret = true
                local filename = vim.api.nvim_buf_get_name(bufnr)
                local fsize = vim.fn.getfsize(filename)
                -- file size greater than 10k can't be previewed automatically
                if fsize > 10 * 1024 then
                    ret = false
                end
                return ret
            end
        }
    })
```
I'm refactoring bqf recently, may change the callback api. So I only add the feature without documentation, feel free to share your option here.

**Comment by jaekyeom** [comment]
I have almost no knowledge about the internals of nvim-bqf, but as a user, I'm very happy with this callback approach!
Thanks for such a quick update.
