### ISSUE TITLE
Toggle the Quickfix list

### ISSUE THREAD

**Issue by Trid-collab** [kevinhwang91/nvim-bqf#35]
Is there anyway I can have a keybind option to toggle the Quickfix list open and close through this plugin

**Comment by kevinhwang91** [comment]
No, there's no reason should be added into bqf.

bqf only solves the drawback of the native quickfix that lacking previewer, filter, and so on.

I think you can borrow the code from the Internet to do the toggle action and rebuild your own qf configuration. Like writing them into `~/.config/ftplugin/qf.vim` or `~/.config/after/ftplugin/qf.vim`.

**Comment by ram02z** [comment]
@Trid-collab I use this to toggle the quickfix list 
```lua
M.toggle_qf = function()
  local qf_open = false
  for _, win in pairs(vim.fn.getwininfo()) do
    if win["quickfix"] == 1 then
      qf_open = true
    end
  end
  if qf_open == true then
    vim.cmd("cclose")
    return
  end
  if not vim.tbl_isempty(vim.fn.getqflist()) then
    vim.cmd("copen")
  end
end
```

**Comment by timsofteng** [comment]
> @Trid-collab I use this to toggle the quickfix list
> 
> ```lua
> M.toggle_qf = function()
>   local qf_open = false
>   for _, win in pairs(vim.fn.getwininfo()) do
>     if win["quickfix"] == 1 then
>       qf_open = true
>     end
>   end
>   if qf_open == true then
>     vim.cmd("cclose")
>     return
>   end
>   if not vim.tbl_isempty(vim.fn.getqflist()) then
>     vim.cmd("copen")
>   end
> end
> ```

Hello. Does it save last cursor position in list?

**Comment by kevinhwang91** [comment]
> > @Trid-collab I use this to toggle the quickfix list
> > ```lua
> > M.toggle_qf = function()
> >   local qf_open = false
> >   for _, win in pairs(vim.fn.getwininfo()) do
> >     if win["quickfix"] == 1 then
> >       qf_open = true
> >     end
> >   end
> >   if qf_open == true then
> >     vim.cmd("cclose")
> >     return
> >   end
> >   if not vim.tbl_isempty(vim.fn.getqflist()) then
> >     vim.cmd("copen")
> >   end
> > end
> > ```
> 
> Hello. Does it save last cursor position in list?

```lua
if vim.b.bqf_enabled then
    vim.api.nvim_feedkeys([['"]], 'im', false)
end

```

**Comment by szachy113** [comment]
The following worked for me in Lua 😉
```lua
local M = {}

M.toggle_qf = function()
	for _, win in pairs(vim.fn.getwininfo()) do
		if win["quickfix"] == 1 then
			vim.cmd("close " .. win.winnr)
			return
		end
	end

	vim.diagnostic.setloclist()
end

return M
```
