### ISSUE TITLE
Removing current quickfix list from stack

### ISSUE THREAD

**Issue by lcrockett** [kevinhwang91/nvim-bqf#36]
**Describe the solution you'd like**
It would be great if `nvim-bqf` would support a function to remove the currently opened quickfix list from the stack. If there are no other quickfix lists remaining in the stack, it would be best to close quickfix alltogether, if there are other quickfix lists available in the stack, it would be most practical to move to the most nearby list.

This allows for a more efficient use of quickfix lists as old ones do not keep lingering around making it more difficult to find your way through quickfix lists if you have quite a few.

**Describe alternatives you've considered**
I currently use a filetype plugin for filetype `qf` to set a keymap that clears *all* quickfix lists. This is more of a nuclear action as it clears all quickfix lists in the stack all together. I'm not sure if it's possible to just clear the current quickfix list from the stack, so if this can be done Neovim native that will be fine too.

`vim.api.nvim_set_keymap('n', 'C', '<CMD>call setqflist([], "f")<CR><CMD>cclose<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })`

**Additional context**
Cheers on the plugin, great work !

**Comment by kevinhwang91** [comment]
No, we can't free specify qflist from the stack. But maybe have a workaround for you.

How can you produce qflist? If not `call setqflist({list} [, {action}[, {'nr': '$'}]])`, I think you can run `colder` before closing qf.

Suppose current nr = 5, previous nr = 4

1. run `colder` and `close`
2. `cw` will open the qflist which nr = 4
3. If the new qflist is created without `nr = '$'`, the nr = 5 will be overridden.

**Comment by lcrockett** [comment]
Thanks for the useful feedback. I've tried a few things and took your suggestions into account. In the end i've decided to map buffer-local keys (`[0-9]`) to each individual quickfix in the stack. This allows me to efficiently move in between lists and is actually more practical IMHO.

Additionally I created an additional keymap to clear the current list in the stack, aside of having the nuclear option of freeing all lists in the stack. See below:

```lua
vim.api.nvim_buf_set_keymap(0, 'n', '-', '<CMD>lua _G.self_function_global_quickfix_set_title()<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', '1', '<CMD>1chistory<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', '2', '<CMD>2chistory<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', '3', '<CMD>3chistory<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', '4', '<CMD>4chistory<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', '5', '<CMD>5chistory<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', '6', '<CMD>6chistory<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', '7', '<CMD>7chistory<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', '8', '<CMD>8chistory<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', '9', '<CMD>9chistory<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', 'C', '<CMD>call setqflist([], "r", {"id" : getqflist({"id" : 0}).id, "items" : []})<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', 'N', '<CMD>call setqflist([], "f")<CR><CMD>cclose<CR><CMD>echon \'\'<CR>', { noremap = true, silent = true })
vim.api.nvim_buf_set_keymap(0, 'n', 'q', '<CMD>cclose<CR>', { noremap = true, silent = true })
```

Cheers
