### ISSUE TITLE
Why not map <esc> to cclose on filetype qf?

### ISSUE THREAD

**Issue by hungrybirder** [kevinhwang91/nvim-bqf#38]
Hi, 
Thank you for this great plugin.

Would you add mapping for `<esc>` to `cclose` in this plugin ?
It's easy to close the quickfix window.

I add some code to do this.
```vim
augroup BQF
  au!
  au FileType qf nnoremap <esc> :cclose<CR>
augroup END
```

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-bqf/pull/37 FYI, `h ftplugin` which is better than `au FileType qf`.

To be honest,  add this remap is not hard for users or bqf, but I want users to RTFM. I don't want to become a users' nanny.
quickfix is neo/vim feature, bqf never change the existed features.

**Comment by hungrybirder** [comment]
> #37 FYI, `h ftplugin` which is better than `au FileType qf`.
> 
> To be honest, add this remap is not hard for users or bqf, but I want users to RTFM. I don't want to become a users' nanny.
> quickfix is neo/vim feature, bqf never change the existed features.

yes, I'm using ftplugin to do this. 
Okay, fair enough.
Thank you.
