### ISSUE TITLE
How can I open item in a split while keeping the quickfix open

### ISSUE THREAD

**Issue by nadeemkhedr** [kevinhwang91/nvim-bqf#39]
I know bqf provides `C-x` and `C-v` to open the selected item a split, but when I press these shortcuts the quickfix is closed, how can i keep it open after pressing either shortcuts?

**Comment by kevinhwang91** [comment]
There's a layout issue for splitting and keeping qf window. However, you can wrap the bqf mapping.

```lua
    require('bqf').setup({
        auto_enable = true,
        func_map = {split = [[<Plug>(BqfSplit)]]},
    })
```

`cat ~/.config/nvim/after/ftplugin/qf.vim`
```vim
map <buffer> <C-x> <Plug>(BqfSplit)<Cmd>cw<CR>
```

**Comment by timsofteng** [comment]
@kevinhwang91 may we some kind of option to replace this strange workaround?
