### ISSUE TITLE
Feedback: I can't tell why I should use this library

### ISSUE THREAD

**Issue by dbalatero** [kevinhwang91/nvim-bqf#4]
Hello! I've landed on this library about a half-dozen times while looking for new plugins for Neovim. Every time I read the README however, I never walk away with an answer to "what will this plugin actually do for me?"

This list of features here doesn't really trigger anything in my mind: https://github.com/kevinhwang91/nvim-bqf#features

If you expand this out into real-world stories, it would probably help sell the library better!

Example:

By default, <some feature> of the quickfix window is really hard to use for <reason>, <another reason>. This library lets you <do something awesome> to make that experience way better, simply by <pressing some key, setting up some config, whatever>.

**Comment by kevinhwang91** [comment]
Thank you very much for your feedback, I really feel that I didn't do well before, I have updated the readme and give some reasons for why should use bqf.

**Comment by dbalatero** [comment]
Great, thanks so much for adding this!

I just installed it and already I love:

* preview window
* `zf` to open in FZF
