### ISSUE TITLE
Separate out "magic window" functionality into a new plugin

### ISSUE THREAD

**Issue by pianocomposer321** [kevinhwang91/nvim-bqf#40]
Kind of a weird request, but I've found myself abusing floating windows to avoid jarring other split windows for a number of different things, not just quickfix lists. It would be nice if this functionality was in a separate plugin that could wrap other commands that open splits in the bottom pane. My most common use case would be for a terminal.

IDK if this is actually possible, but I thought I'd ask, since to my knowledge this is the only plugin that does this with any window at all.

**Comment by kevinhwang91** [comment]
I have thought of this idea since bqf is developing. But I figure out only `preview window` needs `magic window`. 

As you mention, you need your new terminal window to keep your window layout and view `magic`, which is slightly different from quickfix window. 

qf is always as a callee, but the terminal is as a caller. You can wrap the open function to do what you want, but qf is called by others,  that's why `magic window` is developed.

As I said above, I am not sure other features truly need `magic window`, I will leave this request low priority, free feel to correct me if I am wrong.

**Comment by kevinhwang91** [comment]
I forgot closing window will extend other windows' size, maybe you are right. I will separate out `magic window` in the future. (maybe next week?)

**Comment by kevinhwang91** [comment]
The current state is WIP. I'm very busy recently.
You can try `dev` branch and combine the below snippet should work for a terminal.

```lua
function _G.test_term()
    local pwinid = vim.fn.win_getid(vim.fn.winnr('#'))
    local cur_winid = vim.api.nvim_get_current_win()
    if pwinid ~= cur_winid and vim.fn.winnr('$') > 1 then
        if vim.fn.win_gettype(cur_winid) == '' then
            require('bqf.magicwin.core').attach(cur_winid, pwinid)
            vim.cmd(
                ([[au BufWinEnter <buffer> lua require('bqf.magicwin.core').attach(%d, %d)]]):format(
                    cur_winid, pwinid))
        end
    end
end
vim.cmd('pa nvim-bqf')
vim.cmd('aug TestMagicWin')
vim.cmd('au!')
vim.cmd([[au TermOpen * lua _G.test_term()]])
vim.cmd('aug END')
```
`10sp | e term://bash` will work.

**Comment by kevinhwang91** [comment]
@pianocomposer321 Have you tried the snippet I provide?

**Comment by kevinhwang91** [comment]
It Will be solved tonight, I'm going to go shopping. It's 10 AM here :)

**Comment by kevinhwang91** [comment]
The above error should be gone now, please use this new snippet:
```lua
function _G.test_term()
    local pwinid = vim.fn.win_getid(vim.fn.winnr('#'))
    local cur_winid = vim.api.nvim_get_current_win()
    if pwinid ~= cur_winid and vim.fn.winnr('$') > 1 then
        if vim.fn.win_gettype(cur_winid) == '' then
            require('bqf.magicwin.handler').attach(cur_winid, pwinid)
            vim.cmd([[au BufWinEnter <buffer> lua require('bqf.magicwin.handler').attach()]])
        end
    end
end
vim.cmd('pa nvim-bqf')
vim.cmd('aug TestMagicWin')
vim.cmd('au!')
vim.cmd([[au TermOpen * lua _G.test_term()]])
vim.cmd('aug END')
```

Some cases that work as unexpected. But so tired today.

**Comment by pianocomposer321** [comment]
Thanks, it seems to be working now!

**Comment by kevinhwang91** [comment]
`dev` is merged to `main` now

**Comment by pianocomposer321** [comment]
Is there any update on this? I'm still using the functionality of nvim-bqf, so having it installed isn't a problem, but it seems strange to rely on a plugin for a completely different set of functionality to make my terminal not jar my splits when I open it...

If you're not planning on doing it yourself, I still might be interested in giving it a try.

**Comment by kevinhwang91** [comment]
I have been waiting for your reply because I assumed that https://github.com/gillyb/stable-windows satisfy your needs.

**Comment by pianocomposer321** [comment]
Sorry about that, I didn't realize you were waiting for me. I haven't actually given it a try, because from your last reply I like your approach to the stabilization better. If you'd like me to give it a try and let you know what I think before you proceed, I'm more than willing to do that.

**Comment by kevinhwang91** [comment]
You should try it, which is dedicated to stabilizing windows.

**Comment by kevinhwang91** [comment]
https://github.com/neovim/neovim/pull/19243

**Comment by pianocomposer321** [comment]
Awesome, I may have to switch to nightly once that gets merged.
