### ISSUE TITLE
bqf preview window became a seperate floating windows after press `ctrl-o` in quickfix window

### ISSUE THREAD

**Issue by leoatchina** [kevinhwang91/nvim-bqf#41]
- `nvim --version`: 0.5,  stable version
- Operating system/version: windows-wsl , debian9, windows
- updated to the latest dev branch commits

**Describe the bug**
I found this bug is imported by latest commits.
Actually, on my debian system , before `PlugUpdate` this morning, I did `Ctrl-o` the preview windows worked and disappeared normally, but after the updating , things became wired.

**To Reproduce using `nvim -u mini.vim`**
Not need , this bug is invoked by some latest commits.

1. Seach,
2. mv cursor to quickfix windows, then the preview window popup
3. press `ctrl-o`,   please notice I did not enter fzf mode.

**Expected behavior**

**Screenshots**

![Snipaste_2021-09-25_05-50-52](https://user-images.githubusercontent.com/4470821/134744360-245c3b51-7aa7-477b-b48b-8c3d7c0e0885.png)
You can see the preview window become a no-related window, acctually the windows is `splited`
![image](https://user-images.githubusercontent.com/4470821/134744400-0843641e-0daa-4aff-8ee9-fc66e697f510.png)

**Additional context**
I have setted this bug  by lazy qf buffer nmaps 
```
au FileType qf nmap <buffer> i zf
au FileType qf nmap <buffer> <C-o> T
au FileType qf nmap <buffer> <C-t> t
```

**Comment by kevinhwang91** [comment]
Fixed
