### ISSUE TITLE
Preview syntax highlighting not working, unless buffer has already been opened

### ISSUE THREAD

**Issue by lcrockett** [kevinhwang91/nvim-bqf#43]
### Neovim version (nvim -v | head -n1)

NVIM v0.5.1

### Operating system/version

macOS 11.5.2 + Ubuntu 20.04 LTS

### How to reproduce the issue

1. Send items to Quickfix list
2. Scroll through Quickfix items in order to see preview via `nvim-bqf`
3. Conclude syntax highlighting is not working

### Expected behavior

I would expect syntax highlighting to work in the preview window without having to open the buffer prior to opening the Quickfix list

### Actual behavior

There is no syntax highlighting applied when previewing files via the Quickfix list. However, if I already had the buffer opened, or would open the buffer prior to using the Quickfix list, syntax highlighting does work. See the different in the screenshots below:

Example :: Previewing `markdown.lua` via Quickfix :: Syntax highlighting works because the buffer `markdown.lua` was already opened
![image](https://user-images.githubusercontent.com/58056722/140622670-cd100c7b-9197-4c52-9ee8-0f798827bf86.jpeg)

Example :: Previewing `marks.lua` via Quickfix :: Syntax highlighting does not work because the buffer has not been opened
![image](https://user-images.githubusercontent.com/58056722/140622674-b759e65e-43e6-414a-a4ac-14dc231052b0.jpeg)

**Comment by kevinhwang91** [comment]
Uninstall `nathom/filetype.nvim` or patch below snippet to it.
```diff
diff --git a/lua/filetype/init.lua b/lua/filetype/init.lua
index 56e8bde..9392cdf 100644
--- a/lua/filetype/init.lua
+++ b/lua/filetype/init.lua
@@ -128,10 +128,13 @@ function M.resolve()
 
     local expand = vim.fn.expand
 
-    local filename = expand("%:t")
-    if filename == "" then
-        return
-    end
+    local filename = expand('<amatch>')
+     if filename == "" then
+        filename = expand("%:t")
+        if filename == "" then
+            return
+        end
+     end
 
     -- Extension
     local ext = filename:match("%S%.(%w+)$")
```

I'm not interested in that plugin.

**Comment by lcrockett** [comment]
Spot on, that was indeed the culprit and i've removed the `filetype.nvim`.

Unrelated question to this; in your `bqf-demo.mp4` video it shows the Quickfix list with clear separation between the 3 columns (filename | position | content) and adequate spacing. Is that part of `nvim-bqf` functionality ? If so, is there documentation available on configuring it like that ?

Cheers on the prompt solution !

**Comment by kevinhwang91** [comment]
> Unrelated question to this; in your `bqf-demo.mp4` video it shows the Quickfix list with clear separation between the 3 columns (filename | position | content) and adequate spacing. Is that part of `nvim-bqf` functionality ? If so, is there documentation available on configuring it like that ?

No. It's my qftf setting. `:h qftf`

```lua
function _G.qftf(info)
    local items
    local ret = {}
    if info.quickfix == 1 then
        items = fn.getqflist({id = info.id, items = 0}).items
    else
        items = fn.getloclist(info.winid, {id = info.id, items = 0}).items
    end
    local limit = 31
    local fname_fmt1, fname_fmt2 = '%-' .. limit .. 's', '…%.' .. (limit - 1) .. 's'
    local valid_fmt = '%s │%5d:%-3d│%s %s'
    for i = info.start_idx, info.end_idx do
        local e = items[i]
        local fname = ''
        local str
        if e.valid == 1 then
            if e.bufnr > 0 then
                fname = fn.bufname(e.bufnr)
                if fname == '' then
                    fname = '[No Name]'
                else
                    fname = fname:gsub('^' .. vim.env.HOME, '~')
                end
                -- char in fname may occur more than 1 width, ignore this issue in order to keep
                -- performance
                if #fname <= limit then
                    fname = fname_fmt1:format(fname)
                else
                    fname = fname_fmt2:format(fname:sub(1 - limit))
                end
            end
            local lnum = e.lnum > 99999 and -1 or e.lnum
            local col = e.col > 999 and -1 or e.col
            local qtype = e.type == '' and '' or ' ' .. e.type:sub(1, 1):upper()
            str = valid_fmt:format(fname, lnum, col, qtype, e.text)
        else
            str = e.text
        end
        table.insert(ret, str)
    end
    return ret
end
```

**Comment by lcrockett** [comment]
Works great, thanks for that !
