### ISSUE TITLE
Allow to add a custom opener to func_map

### ISSUE THREAD

**Issue by przepompownia** [kevinhwang91/nvim-bqf#45]
### Feature description

Hi,

it seems for me (i'm fresh in Lua) that the set of allowed keys of `func_map` is restricted to `action_funcref` from `keymap`.

I'd like to attach a custom opener that does an action similar to `tab drop` (see links below).

### Describe the solution you'd like

Please allow to attach a function (as the opener) that get the path, (and, if provided) line and column to allow make a customized jumping.

### Additional context

https://github.com/neovim/neovim/issues/14567
https://github.com/przepompownia/vim-arctgx/blob/master/plugin/tab.vim#L11

**Comment by kevinhwang91** [comment]
What's different between `drop` and `tab drop`? If they are the same, I can add a `drop` action.

**Comment by kevinhwang91** [comment]
Oh, my bad. `tab drop` will open a new tab for target buffer if the buffer is not displayed but `drop` will switch to target buffer in the current window.

**Comment by przepompownia** [comment]
Maybe `tab drop` could be present by default in `action_funcref` but it is not sufficient for me - I am not use `tab drop` because of the bug mentioned above (that exist in traditional Vim too).

**Comment by kevinhwang91** [comment]
I have added three new jump commands. All of them will close qf window, you can wrap the command by yourself.

FYI: https://github.com/kevinhwang91/nvim-bqf/issues/39

**Comment by przepompownia** [comment]
I see that 
```vim
lua require('bqf.qfwin.handler').open(true, 'TabDrop')
```
works for me when I call it manually from the cmdline, but filetype autocommand
```vim
nmap <buffer> <CR> <Cmd>lua require('bqf.qfwin.handler').open(true, 'TabDrop')<CR>
```
seems to be overwritten by `<Cmd>lua require('bqf.qfwin.handler').open(false)<CR>`

How to attach such custom funcref? Why not to allow overriding `action_funcref` from config (if it's currently impossible)?

**Comment by kevinhwang91** [comment]
> I see that
> 
> ```viml
> lua require('bqf.qfwin.handler').open(true, 'TabDrop')
> ```
> 
> works for me when I call it manually from the cmdline, but filetype autocommand

No `TabDrop` but `tab drop`

> ```viml
> nmap <buffer> <CR> <Cmd>lua require('bqf.qfwin.handler').open(true, 'TabDrop')<CR>
> ```
> 
> seems to be overwritten by `<Cmd>lua require('bqf.qfwin.handler').open(false)<CR>`
> 
> How to attach such custom funcref? Why not to allow overriding `action_funcref` from config (if it's currently impossible)?

You can, RTFM

**Comment by przepompownia** [comment]
> 

> No `TabDrop` but `tab drop`

`tab drop`  causes unwanted side effects (see links in the initial message) so I need to use such custom replacement.

**Comment by kevinhwang91** [comment]
> FYI: #39

**Comment by przepompownia** [comment]
```lua
require('bqf').setup({
  auto_enable = true,
  func_map = {
    open = '',
  }
})
```
allows to disable `nmap <CR>` defined by the plugin so now I can use the mapping mentioned above.
