### ISSUE TITLE
Creates unnamed buffer in buffer tab plugins (ex: barbar)

### ISSUE THREAD

**Issue by bashirsouid** [kevinhwang91/nvim-bqf#46]
### Neovim version (nvim -v | head -n1)

NVIM v0.6.0-dev+1993-g1dbbaf89b

### Operating system/version

macOS 12.0.1

### How to reproduce the issue

1. Install [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf) and [barbar.nvim](https://github.com/romgrk/barbar.nvim)
2. Open up location list. Bask in the glory that is vim-bqf.
3. Notice there is a weird extra unnamed buffer visible that is the same contents as the loc list window. If you close it then you get the file open in both the original split and lower split where location list used to be.
...
![image](https://user-images.githubusercontent.com/2036949/143658918-c558a643-72ee-4ebb-a86f-bec82b929920.png)

### Expected behavior

The buffer created by vim-bqf not visible in buffer tab.

It could be ignored in barbar as there is functionality for excludes. But you can't exclude an unnamed buffer really.

Maybe the vim-bqf buffer should have a specific discoverable name?

### Actual behavior

vim-bqf creates a new unnamed buffer that you can accidentally tab towards which can break the layout.

**Comment by bashirsouid** [comment]
barbar also allows exclude by filetype so maybe vim-bqf could set a special filetype like "list"?

**Comment by kevinhwang91** [comment]
I disable nvim-bqf to make quickfix window vanilla and then use `copen` to open a quickfix window that make barbar always shows a new tab.
I think you should open an issue to barbar.

**Comment by bashirsouid** [comment]
Oh, you are right, this is barbar issue. Sorry for the noise, marking this one as closed.
