### ISSUE TITLE
windows resizes

### ISSUE THREAD

**Issue by 0xRZ** [kevinhwang91/nvim-bqf#47]
### Neovim version (nvim -v | head -n1)

NVIM v0.6.0-dev+640-gb51b0aecc

### Operating system/version

linux

### How to reproduce the issue

When using this plugin `equalalways` options is not respected. It's handy when window sizes are equalised after closing quickfix window. As i see in `:help equalalways` it says
```
If a window size is specified when creating a new window sizes are
currently not equalized (it's complicated, but may be implemented in the future).
```
I tried setting 
```
require('bqf').setup(
{
 	auto_enable = {
 	        default = true,
 	},
 	auto_resize_height = {
        	default = false,
     	},
 })
```
But it does not help. 
Is it possible to maybe make parameter of not specifying window size when creating quick-fix window to respect `equalalways`?

### Expected behavior

Windows height made equal after closing quick-fix window

![Peek 2021-11-29 14-46](https://user-images.githubusercontent.com/46892933/143869131-aa06bd16-6b2e-40e1-ad51-b3037bb09999.gif)

### Actual behavior

As you see top left window is left shorter after closing quick-fix window.

![Peek 2021-11-29 15-13](https://user-images.githubusercontent.com/46892933/143868723-ee5725cd-f05d-4b44-9f77-18809f1138bc.gif)

**Comment by kevinhwang91** [comment]
This is magic window feature. `magic_window = false`

**Comment by 0xRZ** [comment]
@kevinhwang91 oh you right, sorry, i didn't read the docs carefully.
