### ISSUE TITLE
[Conflict With quickfix-reflector.vim] Once with `quickfix-reflector.vim` enabled, the auto preview not work

### ISSUE THREAD

**Issue by hiberabyss** [kevinhwang91/nvim-bqf#48]
### Neovim version (nvim -v | head -n1)

NVIM v0.5.1

### Operating system/version

macOS 12.0.1

### How to reproduce the issue

Install both nvim-bqf and quickfix-reflector.vim, then search something, the auto-preview not work when switch quickfix item, and the preview window will keep there after `cclose`.

If call `BqfEnable` manually, everything will be OK.

### Expected behavior

Expect also work with `quickfix-reflector.vim` installed.

### Actual behavior

auto-preview not work when with `quickfix-reflector.vim`

**Comment by kevinhwang91** [comment]
No idea how to fix it. quickfix-reflector.vim will run `write!` which will make all `<buffer>` aug dispear, maybe an upstream bug.
Choose one plugin you like and uninstall another.

FYI: After setting `qftf`, quickfix-reflector.vim won't work.

**Comment by RayZ0rr** [comment]
> FYI: After setting `qftf`, quickfix-reflector.vim won't work.

**Just a small note** :- 

I have set `qftf` using the instructions in [format-new-quickfix](https://github.com/kevinhwang91/nvim-bqf#format-new-quickfix)

But still [quickfix-reflector.nvim](https://github.com/stefandtw/quickfix-reflector.vim) is working without any issues no far (I have not installed `nvim-bqf`. Only using the `qftf` function provided).
