### ISSUE TITLE
cannot customise Function commands

### ISSUE THREAD

**Issue by gennaro-tedesco** [kevinhwang91/nvim-bqf#5]
- `nvim --version`:
```
nvim --version
NVIM v0.5.0-dev+1083-g1aec5ba85
Build type: Release
LuaJIT 2.1.0-beta3
```

**Describe the bug**
As per [documentation](https://github.com/kevinhwang91/nvim-bqf#function-table) one can customise Function commands via `lua require('bqf').setup({func_map = {}})`. It is however unclear what the correct string grammar must be, I have tried all possible cominations of quotation marks and the like but nothing works. In particular I am trying, for example
```
lua require('bqf').setup({openc = {'<CR>'}})
```
to no avail. `lua require('bqf').setup({'openc' = {'<CR>'}})` generates an error and removing quotation marks from everywhere seems to have no effect either.

**Expected behavior**
Provide a clear example of command customisation that can be copied and pasted.

**Additional context**

**Comment by kevinhwang91** [comment]
```lua
require('bqf').setup({
    func_map = {
        open = 'o',
        openc = '<CR>',
    }
})
```
You can reference [customize-configuration](https://github.com/kevinhwang91/nvim-bqf#customize-configuration) section.
I will improve the doc later :) Thanks for your feedback.

**Comment by gennaro-tedesco** [comment]
Sorry to re-open: are you sure the configuration is correct and is in fact being overridden? I have copy-pasted your command and the re-mapping does not work.

**Comment by kevinhwang91** [comment]
show your minimal config here.

**Comment by gennaro-tedesco** [comment]
I have reduced all to the following `init.vim`
```
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/nvim-bqf'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()

lua require('bqf').setup({func_map = {open = 'o', openc = '<CR>', }})
```
The plugin per sé works fine (I have tried it with `Plug 'neoclide/coc.nvim', {'branch': 'release'}` as well to display their quickfix lists and all is good), it is only the customised configuration that seems not to have any effect. In the case at hand the above configuration does remove 'o' from opening and closing the quickfix window, however it does not transfer this functionality to `<CR>`. 

Perhaps really easily one must specify `<CR>` with a different grammar (according to the way you are parsing the right hand side into a Lua table)?

**Comment by kevinhwang91** [comment]
I can't reproduce the issue from your config. You should make sure that `map <buffer>` with minimal config output like below:
```log
n  o            @<Cmd>lua require('bqf.jump').open(false)<CR>
n  <CR>         @<Cmd>lua require('bqf.jump').open(true)<CR>
```
`true` means close the quickfix window.

**Comment by gennaro-tedesco** [comment]
Unfortunately I still see the original values (namely `true` and `false` being swapped in the above example with `map <buffer>`). Nevermind, thank you for looking into it nevertheless!
