### ISSUE TITLE
Cursor jumps back to original location when closing quickfix window after opening any item

### ISSUE THREAD

**Issue by chiendo97** [kevinhwang91/nvim-bqf#50]
### Neovim version (nvim -v | head -n1)

NVIM v0.6.1

### Operating system/version

macOS 11.6.2 (20G314)

### How to reproduce the issue

1. Open any new file with any context
2. Find a word with grep `:grep window .`
3. Open a quickfix window with `:copen`
4. Navigate to any new item (not the first item)
5. Press `enter` to go to new location where that item is
6. Use `:cclose` to close the quickfix window

### Expected behavior

The cursor still stays at its current location after closing the quickfix window 

### Actual behavior

The cursor still jumps back to the previous location

**Comment by kevinhwang91** [comment]
Thanks, fix now.
