### ISSUE TITLE
Nothing happened after I press enter key when I signed some items in fzf mode.

### ISSUE THREAD

**Issue by rhcher** [kevinhwang91/nvim-bqf#52]
### Neovim version (nvim -v | head -n1)

 NVIM v0.7.0-dev+1055-g2db0a5207

### Operating system/version

wsl2 Arch

### How to reproduce the issue

1. open a file and create a qflist
2. press `zf` to go to fzf mode and use `tab` key to selected some items.
3. Then press `enter` key, We can notice that nothing happened and the qflist has not been changed.

### Expected behavior

fzf can filter items when I selecte some items and press enter key

### Actual behavior

the qflist not been changed.

**Comment by kevinhwang91** [comment]
Thanks, fixed now.
