### ISSUE TITLE
"Applying" The FZF Filter

### ISSUE THREAD

**Issue by harrisoncramer** [kevinhwang91/nvim-bqf#53]
### Feature description

First of all, awesome plugin! Thank you so much for your hard work.

When using `zf` to filter the quickfix list, it's very easy to type out the filter and then visually inspect the quickfix list to see that it's correct. How can we easily "apply" this filter to create a new quickfix list using this filter?

After typing out an FZF filter, my current workflow is to select the values in the list with `<C-o>` and then pressing `<C-q>` to apply a tab to all of them, and then pressing `zn` to create a new quickfix list with the selected entries.

### Describe the solution you'd like

An easier way of applying an FZF filter to the current quickfix list, to create a _new_ quickfix list with all the values it contains. Ideally this would occur without modifying the original list.

**Comment by harrisoncramer** [comment]
Closing, this is possible by selecting items and then hitting enter, it was recently fixed with #52

**Comment by kevinhwang91** [comment]
Sorry for my careless refactoring.

**Comment by harrisoncramer** [comment]
Dude no worries thank you for the amazing plugin
