### ISSUE TITLE
Option to enable max size preview

### ISSUE THREAD

**Issue by ajitid** [kevinhwang91/nvim-bqf#55]
### Feature description

I quite like max-size preview as upon selecting an item, the cursor stays to that position. 

![anim-rg](https://user-images.githubusercontent.com/26769888/154197029-0738fe3c-e552-4dfa-80ed-aa8ccd20c4b4.gif)
 

### Describe the solution you'd like

I would like a new option under `opts.preview`  or, if possible, assigning a value to existing `opts.preview.win_height` that would make the preview full screen.

### Additional context

**Options I tried**:

- Addding

```vim
lua require"bqf.preview.handler".toggle_mode()
```

in `after/ftplugin/qf.vim`. Using this results in an error when qf is opened.

- Right now, I have to manually press `zp` everytime I open qf list

**Comment by kevinhwang91** [comment]
Have you tried changing the `win_height = 999` in a setup table?

**Comment by ajitid** [comment]
No I didn't. But only because I felt this could be the wrong way to use it.

So I just tried and it works. Should we close the issue then?

**Comment by ajitid** [comment]
This plugin makes vim experience much much better for me. Thank you for working on it!

**Comment by kevinhwang91** [comment]
Enjoy!
