### ISSUE TITLE
default auto_resize_height quickfix height of 10 seems too high

### ISSUE THREAD

**Issue by mccurdyc** [kevinhwang91/nvim-bqf#58]
### Feature description

I love bqf! Thank you for your work on it!

The default auto_resize_height quickfix height of 10 seems too high, could we make it the size of the list or 1 instead of 10?

### Describe the solution you'd like

Quickfix has a default height of the number of items in the quickfix list even when <10 items or if the quickfix is empty, maybe quickfix height is 1.

### Additional context

https://github.com/kevinhwang91/nvim-bqf/blob/bbe21d08c9f8372aa399ea8c3051763ab777f176/README.md#L164

**Comment by kevinhwang91** [comment]
I guess you misunderstand the description of `auto_resize_height`.
Assume we have enabled `auto_resize_height`.

1. List size is 100, `cw 15` will set the height to 15;
2. List size is 5, `cw 15` will set the height to 5;
3. List size is 0, `copen 15` will set the height to 1, because 0 height is not permitted
4. Current list size is 1, previous list size is 15, `cold` will set the height to 10;
4. Current list size is 15, previous list size is 1, `cold` will set the height to 1;

`:h :copen`
> When [height] is given, the window becomes that high
(if there is room).  When [height] is omitted the
window is made ten lines high.

**Comment by mccurdyc** [comment]
@kevinhwang91 thanks!! Unfortunately, I think I still misunderstand.

I have `auto_resize_height` set to `true` and my quickfix list has 2 items, yet my quickfix window is still a height of 10.

I expect it to automatically resize to 2.

How can I ensure that my quickfix is using bqf instead of the normal quickfix window? I've tried `:BqfEnable` in the quickfix window and then re-saved (still no resizing) and I have `auto_enable = true` in my bqf configuration. Is there anything else I can do?

Thanks!

**Comment by kevinhwang91** [comment]
Check out your others plugins that may conflict. try minimal config.

**Comment by mccurdyc** [comment]
If this is just me, I'll close.

**Comment by mccurdyc** [comment]
Confirmed worked as expected with this minimal config and by running this command `vimgrep /\w\+/j % | copen`

https://github.com/mccurdyc/dotfiles/blob/6f350ec2ac4f3923ff2cee61f24a8bc3ef065365/minimal/init.lua

```
local cmd = vim.cmd
local o, wo, bo = vim.o, vim.wo, vim.bo

local function opt(o, v, scopes)
  scopes = scopes or {o_s}
  for _, s in ipairs(scopes) do s[o] = v end
end

local buffer = {o, bo}
local window = {o, wo}

cmd("filetype plugin indent on")

opt("clipboard", "unnamedplus")
opt("swapfile", false, buffer)
opt("title", true)
opt("wrap", false, window)
opt("number", true, window)
opt("linebreak", true, window)
opt("showbreak", "━━")
opt("breakindent", true, window)
opt("tabstop", 2, buffer)
opt("shiftwidth", 2)
opt("expandtab", true, buffer)
opt("shiftround", true)
opt("lazyredraw", true)
opt("colorcolumn", "80", window)
opt("hidden", true)
opt("list", true)
opt("syntax", "enable")
opt("hlsearch", false)
opt("splitbelow", true)
opt("splitright", true)
opt("showmode", false)
opt("foldminlines", 5)
opt("foldmethod", "indent")

require("packer").startup(
  {
    function()
      -- https://github.com/wbthomason/packer.nvim/blob/daec6c759f95cd8528e5dd7c214b18b4cec2658c/doc/packer.txt#L534
      use "wbthomason/packer.nvim"

      use {'kevinhwang91/nvim-bqf'}
    end
  }
)
require('bqf').setup({
        auto_enable = true,
        auto_resize_height = true,
})
```

**Comment by mccurdyc** [comment]
Actually, with these bqf settings, the same test as above presents the unexpected behavior. So I believe there is an issue with these combination of settings.

https://github.com/mccurdyc/dotfiles/commit/6a9ccb8c2de67217fe726e4742d6a1974ba41523

```
local cmd = vim.cmd
local o, wo, bo = vim.o, vim.wo, vim.bo

local function opt(o, v, scopes)
  scopes = scopes or {o_s}
  for _, s in ipairs(scopes) do s[o] = v end
end

local buffer = {o, bo}
local window = {o, wo}

cmd("filetype plugin indent on")

opt("clipboard", "unnamedplus")
opt("swapfile", false, buffer)
opt("title", true)
opt("wrap", false, window)
opt("number", true, window)
opt("linebreak", true, window)
opt("showbreak", "━━")
opt("breakindent", true, window)
opt("tabstop", 2, buffer)
opt("shiftwidth", 2)
opt("expandtab", true, buffer)
opt("shiftround", true)
opt("lazyredraw", true)
opt("colorcolumn", "80", window)
opt("hidden", true)
opt("list", true)
opt("syntax", "enable")
opt("hlsearch", false)
opt("splitbelow", true)
opt("splitright", true)
opt("showmode", false)
opt("foldminlines", 5)
opt("foldmethod", "indent")

require("packer").startup(
  {
    function()
      -- https://github.com/wbthomason/packer.nvim/blob/daec6c759f95cd8528e5dd7c214b18b4cec2658c/doc/packer.txt#L534
      use "wbthomason/packer.nvim"

      use {
        "kevinhwang91/nvim-bqf"
      }
    end
  }
)

require("bqf").setup({
  auto_enable = true,
  magic_window = false,
  auto_resize_height = true,
  preview = {
    auto_preview = false
  },
  func_map = {
    vsplit = "",
    ptogglemode = "z,",
    stoggleup = ""
  },
  filter = {
    fzf = {
      action_for = {["ctrl-s"] = "split"},
      extra_opts = {"--bind", "ctrl-o:toggle-all", "--prompt", "> "}
    }
  }
})
```

**Comment by mccurdyc** [comment]
Actually, with these bqf settings, the same test as above presents the unexpected behavior. So I believe there is an issue with these combination of settings.

https://github.com/mccurdyc/dotfiles/commit/6a9ccb8c2de67217fe726e4742d6a1974ba41523

```
local cmd = vim.cmd
local o, wo, bo = vim.o, vim.wo, vim.bo

local function opt(o, v, scopes)
  scopes = scopes or {o_s}
  for _, s in ipairs(scopes) do s[o] = v end
end

local buffer = {o, bo}
local window = {o, wo}

cmd("filetype plugin indent on")

opt("clipboard", "unnamedplus")
opt("swapfile", false, buffer)
opt("title", true)
opt("wrap", false, window)
opt("number", true, window)
opt("linebreak", true, window)
opt("showbreak", "━━")
opt("breakindent", true, window)
opt("tabstop", 2, buffer)
opt("shiftwidth", 2)
opt("expandtab", true, buffer)
opt("shiftround", true)
opt("lazyredraw", true)
opt("colorcolumn", "80", window)
opt("hidden", true)
opt("list", true)
opt("syntax", "enable")
opt("hlsearch", false)
opt("splitbelow", true)
opt("splitright", true)
opt("showmode", false)
opt("foldminlines", 5)
opt("foldmethod", "indent")

require("packer").startup(
  {
    function()
      -- https://github.com/wbthomason/packer.nvim/blob/daec6c759f95cd8528e5dd7c214b18b4cec2658c/doc/packer.txt#L534
      use "wbthomason/packer.nvim"

      use {
        "kevinhwang91/nvim-bqf"
      }
    end
  }
)

require("bqf").setup({
  auto_enable = true,
  magic_window = false,
  auto_resize_height = true,
  preview = {
    auto_preview = false
  },
  func_map = {
    vsplit = "",
    ptogglemode = "z,",
    stoggleup = ""
  },
  filter = {
    fzf = {
      action_for = {["ctrl-s"] = "split"},
      extra_opts = {"--bind", "ctrl-o:toggle-all", "--prompt", "> "}
    }
  }
})
```

**Comment by mccurdyc** [comment]
As soon as I remove `magic_window = false`, I get the behavior I expect.

**Comment by kevinhwang91** [comment]
Thanks, fixed now.
