### ISSUE TITLE
handler.lua:166: attempt to index local 'qs'

### ISSUE THREAD

**Issue by fannheyward** [kevinhwang91/nvim-bqf#59]
### Neovim version (nvim -v | head -n1)

v0.7.0-dev+1280-gf2e5f509d

### Operating system/version

macOS 12.3

### How to reproduce the issue

nvim-bqf with coc.nvim, `nmap <silent> gr <Plug>(coc-references-used)` with `CocLocationsChange` configs.

```
  autocmd User CocLocationsChange ++nested call s:coc_qf_jump2loc(g:coc_jump_locations)

function! s:coc_qf_jump2loc(locs) abort
  let loc_ranges = map(deepcopy(a:locs), 'v:val.range')
  call setloclist(0, [], ' ', {'title': 'CocLocationList', 'items': a:locs, 'context': {'bqf': {'lsp_ranges_hl': loc_ranges}}})
  let winid = getloclist(0, {'winid': 0}).winid
  if winid == 0
    rightbelow lwindow
  else
    call win_gotoid(winid)
  endif
endfunction
```

steps to reproduce:

1. open any code example, for example coc.nvim `nvim +386 src/workspace.ts`
2. `gr` on `expand` function
3. the first time, works as expected, qf shows
4. `esc` to close qf window
5. `gr` on `expand` again, got error `E315: ml_get: 无效的 lnum: 386`
6. `o` to open any qf item

```
E5108: Error executing lua ...al/share/nvim/plugged/nvim-bqf/lua/bqf/qfwin/handler.lua:166: attempt to index local 'qs' (a nil value)
stack traceback:
        ...al/share/nvim/plugged/nvim-bqf/lua/bqf/qfwin/handler.lua:166: in function 'do_edit'
        ...al/share/nvim/plugged/nvim-bqf/lua/bqf/qfwin/handler.lua:218: in function 'open'
        [string ":lua"]:1: in main chunk
```

### Expected behavior

no errors

### Actual behavior

<img width="1220" alt="截屏2022-03-19 21 17 41" src="https://user-images.githubusercontent.com/345274/159122667-1d04638d-bce8-4fd0-bc8b-0407289a92ce.png">

**Comment by kevinhwang91** [comment]
Yes, the issue is not related nvim-bqf. The issue about quickfix has been existed since https://github.com/neovim/neovim/commit/c9b94188d5f96349566372e8a0ce94e14fd6b549.
You can disable nvim-bqf to confirm what I say above, this issue needs time to explore and find out the root cause.

Fortunately, we can use below Vimscript patch as a workaround
```diff
-rightbelow lwindow
+call timer_start(0, {-> execute('rightbelow lwindow')})
```

or Lua snippet:
```lua
vim.schedule(function()
    vim.cmd('rightbelow lwindow')
end)
```

**Comment by kevinhwang91** [comment]
Or delete `++nested`.

**Comment by fannheyward** [comment]
Thank you.
