### ISSUE TITLE
Why mark 'p' ?

### ISSUE THREAD

**Issue by aj3423** [kevinhwang91/nvim-bqf#6]
It is annoying that it adds a mark `p` after selecting result from quickfix window. 

The code seems to be `cmd('mark p')` in *lua/bqf/preview.lua @ line 95*

I see there is sign feature, is the `p` a feature or bug? If it's feature, maybe make it configurable?

Thanks for the great plugin :)

**Comment by kevinhwang91** [comment]
Thanks for your feedback. It's used for `zo`. I haven't displayed marks in signcolumn, so I didn't discover this issue:)

I have updated the code which never uses a mark.
