### ISSUE TITLE
Support previewing vim-fugitive `:Gclog` entries

### ISSUE THREAD

**Issue by b0o** [kevinhwang91/nvim-bqf#60]
### Feature description

Currently, when the quickfix window is populated by [vim-fugitive](https://github.com/tpope/vim-fugitive)'s `:Gclog` command, vim-bqf's preview window is blank unless the highlighted entry has been manually opened first. I'm guessing it has to do with the special file URIs fugitive uses, which look like `fugitive:///home/maddy/.config/nvim/.git//f0e7c59ec59a25bfe928b555dd8387242d2b810f`.

### Describe the solution you'd like

It would be nice if nvim-bqf could properly preview these vim-fugitive quickfix items.

### Additional context

If the highlighted entry hasn't been manually opened yet:

![2022-03-20_01-47-57_Alacritty](https://user-images.githubusercontent.com/21299126/159154934-901ac3ca-89b5-4378-bebc-8ab754583b01.png)

Once the highlighted entry has been opened:

![2022-03-20_01-48-34_Alacritty](https://user-images.githubusercontent.com/21299126/159154949-830ee41c-c26c-44dc-a9ae-1c000c1a868d.png)

**Comment by kevinhwang91** [comment]
nvim-bqf will never support this feature because of the performance issue. You can use `should_preview_cb` hack what you want. You can also use the below setting to experience how slow it is.

```lua
    require('bqf').setup({
        should_preview_cb = function(bufnr)
            local bufname = vim.api.nvim_buf_get_name(bufnr)
            if bufname:match('^fugitive://') then
                vim.api.nvim_buf_call(bufnr, function()
                    cmd(('noa do fugitive BufReadCmd %s'):format(bufname))
                end)
            end
            return true
        end
    })
```

For me, I use https://github.com/rbong/vim-flog which is a git log wrapper and has the ability to limit the commits.  More importantly, it is an extension based on fugitive.

**Comment by b0o** [comment]
Cool, thank you for the tips, and for the wonderful plugin!

**Comment by b0o** [comment]
I took your hack and hacked it even further - this loads the fugitive buffer asynchronously:

```lua
require('bqf').setup {
  preview = {
    should_preview_cb = function(bufnr)
      local bufname = vim.api.nvim_buf_get_name(bufnr)
      if bufname:match '^fugitive://' then
        local pvs = require 'bqf.preview.session'
        local extmark = require 'bqf.preview.extmark'
        local ts = require 'bqf.preview.treesitter'
        vim.schedule(function()
          vim.api.nvim_buf_call(bufnr, function()
            local fbufnr = pvs.float_bufnr()
            vim.cmd(('do fugitive BufReadCmd %s'):format(bufname))
            pvs.floatbuf_reset()
            ts.disable_active(fbufnr)
            extmark.clear_highlight(fbufnr)
            vim.cmd(('silent lua require"bqf.utils".transfer_buf(%d, %d)'):format(bufnr, fbufnr))
          end)
        end)
      end
      return true
    end,
  },
}
```

I copied some code from `bqf.preview.handler.open()` to do this, I'm sure there's a better way but this works well enough for me.

**Comment by kevinhwang91** [comment]
Please update the code which is convenient to hack.

```lua
    local bqf_pv_timer
    require('bqf').setup {
        preview = {
            should_preview_cb = function(bufnr, qwinid)
                local bufname = vim.api.nvim_buf_get_name(bufnr)
                if bufname:match '^fugitive://' and not vim.api.nvim_buf_is_loaded(bufnr) then
                    if bqf_pv_timer and bqf_pv_timer:get_due_in() > 0 then
                        bqf_pv_timer:stop()
                        bqf_pv_timer = nil
                    end
                    bqf_pv_timer = vim.defer_fn(function()
                        vim.api.nvim_buf_call(bufnr, function()
                            vim.cmd(('do fugitive BufReadCmd %s'):format(bufname))
                        end)
                        require('bqf.preview.handler').open(qwinid, nil, true)
                    end, 60)
                end
                return true
            end
        }
    }
```

**Comment by b0o** [comment]
Awesome, much cleaner. Thank you!
