### ISSUE TITLE
error with fzf module

### ISSUE THREAD

**Issue by djavrell** [kevinhwang91/nvim-bqf#64]
### Neovim version (nvim -v | head -n1)

NVIM v0.8.0-dev+1638-ga2d4b862f

### Operating system/version

macOS 12.3

### How to reproduce the issue

add items in the quick fix list, use `zf`

<img width="1278" alt="Screenshot 2022-05-24 at 09 30 36" src="https://user-images.githubusercontent.com/7889450/169974306-056d5462-accb-4504-9c98-d58dba414061.png">

I dig it a bid to understand what's going on.
In `lua/bqf/utils.lua` in method `synKeyword` L305, there is a match on the result of `syn iskeyword` witch expect a string in english, but mine is in french, which end up in a nil value, and then in `genIsKeyword` L328, getting the length is impossible.

I "fixed" this bug in local by setting the return value of `synKeyword` to `return isKeyword or ""`.
But I don't know if this is the right way to do it or not ?

### Expected behavior

no error when opening fzf module in bqf

### Actual behavior

I have an error when using `zf`

**Comment by kevinhwang91** [comment]
What's the output of your PC running `syntax iskeyword` in an empty buffer.

**Comment by djavrell** [comment]
I have `"iskeyword n'est pas activé"` as output

**Comment by kevinhwang91** [comment]
Fixed now.
