### ISSUE TITLE
Can nvim-bqf shorten file paths similar to vim-qf?

### ISSUE THREAD

**Issue by kiryph** [kevinhwang91/nvim-bqf#65]
### Feature description

[vim-qf](https://github.com/romainl/vim-qf) can shorten filepaths for better legibility.

Can nvim-bqf do something similar, e.g. relative to the current pwd?

### Describe the solution you'd like

Shorten the filepaths for better legibility.

**Comment by kiryph** [comment]
Apparently, it can already. Is it documented?

**Comment by kevinhwang91** [comment]
Have you sovled?

**Comment by kiryph** [comment]
I might have fixed it by changing pwd. Does nvim-bqf have actually a path shortening feature? 

vim-qf describes its shorten path feature as following:
```
------------------------------------------------------------------------------
                                                          *'g:qf_shorten_path'*
Value: numeric                                                               ~
Default: 1                                                                   ~

Enables or disables shortening of the file paths in the location/quickfix
window.

With the option set to `0` (vanilla Vim):
>
    very/long/path/with/lots/of/subdirectories/filename.ext|87 col 22| …
With the option set to `1` (vim-qf default):
>
    v/l/p/w/l/o/s/filename.ext|87 col 22| …
With the option set to `3` (Vim v8.2.1741 or above):
>
    ver/lon/pat/wit/lot/of/sub/filename.ext|87 col 22| …
Add the line below to your vimrc to change the default value:
>
    let g:qf_shorten_path = 0
<
```
I am not sure whether I want it exactly as vim-qf. I think only for long paths it should be abbreviated. So there should be a threshold setting and then maybe  a number for the number of characters used to display a shortened path.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-bqf#customize-quickfix-window-easter-egg

Program by yourself.

**Comment by kiryph** [comment]
Thanks for the pointer. I will have a look into this.
