### ISSUE TITLE
Rebuild syntax for quickfix

### ISSUE THREAD

**Issue by strdr4605** [kevinhwang91/nvim-bqf#66]
### Neovim version (nvim -v | head -n1)

NVIM v0.7.0

### Operating system/version

macOS 12.3.1

### How to reproduce the issue

I know this is not related to the plugin but I would like to fix this.
I did **Format new quickfix**. 
But then I add `~/.config/nvim/syntax/qf.vim` nothing happens.
I even tried to change the file in ` /opt/homebrew/Cellar/neovim/0.7.0/share/nvim/runtime/syntax`.

[My nvim config](https://github.com/strdr4605/.dotfiles/blob/master/nvim/init.lua) if it helps.

### Expected behavior

Expected quickfix colors to be different

### Actual behavior

<img width="931" alt="Screenshot 2022-05-28 at 11 13 33" src="https://user-images.githubusercontent.com/16056918/170817188-ff013bad-acd3-469a-a768-64c912461550.png">

**Comment by kevinhwang91** [comment]
`    local validFmt = '%s │%5d:%-3d│%s %s'`
