### ISSUE TITLE
Support for fzf-lua

### ISSUE THREAD

**Issue by adworacz** [kevinhwang91/nvim-bqf#73]
### Feature description

This plugin works great if you're using the original `fzf.vim` from junegunn. 

Having switched over to [fzf-lua](https://github.com/ibhagwan/fzf-lua), I've been very happy with the extended support (especially around LSP integration etc).

Would it be possible to support the `fzf-lua` plugin as an alternative to the original `fzf.vim` plugin, so users don't have to install both?

### Describe the solution you'd like

Integration with [fzf-lua](https://github.com/ibhagwan/fzf-lua).

**Comment by kevinhwang91** [comment]
bqf requires `fzf` not `fzf.vim`.

**Comment by adworacz** [comment]
Ahhh this was my mistake. `fzf-lua` is able to use the natively installed `fzf` without the additional Vim plugin, so I didn't have it installed.

Apologies for the mix up. I've added a corresponding `requires` on my local `fzf` install and `bqf` is working fine now.

**Comment by gennaro-tedesco** [comment]
> I've added a corresponding requires on my local fzf install and bqf is working fine now.

Could you expand on what you've required specifically? I am after the same problem and I keep running into the error

> fzf#run function not found. You also need Vim plugin from the main fzf repository

which makes me think `fzf.vim` is still needed (but apparently not, as I understand).

**Comment by franckrasolo** [comment]
@gennaro-tedesco is right, both `fzf` and `fzf.vim` are needed. I was only able to enter the `fzf` mode after adding them as dependencies:

```lua
{
  "kevinhwang91/nvim-bqf",
  ft = "qf",
  event = "VeryLazy",
  dependencies = { "ibhagwan/fzf-lua", "junegunn/fzf", "junegunn/fzf.vim" },
  opts = {},
}
```
