### ISSUE TITLE
Save, load and manage QuickFix lists!

### ISSUE THREAD

**Issue by perseoGI** [kevinhwang91/nvim-bqf#76]
### Feature description

Hi there! Awesome job :)

I'm looking for a Lua solution to save the current QF list and then restore it. 
It is pretty common while using the built in LSP, to see references of for example a variable while iterating over the QF list. 
Doing so, LSP will override the current QF list loosing all your filtered data.

### Describe the solution you'd like

I'm not sure if it is a native way of storing and reloading a QF list but it will be pretty neat if this pluggin could have some mappings to manage your QF lists, having the possibility of: 

- Store a QF list with a name
- Load a QF list given a name, maybe listing it on Telescope or on another QF list xD
- Optional: having the availability of even mixing multiple QF lists all in one!

### Additional context

Thanks again <3

**Comment by perseoGI** [comment]
Okey, I've already found a native way to accomplish one of my dilemma.
- colder: go to last QF list
- cnewer: go to next QF list

This is nice, but could be done better like this plugin improves native QF list :)

**Comment by kevinhwang91** [comment]
`vim.lsp.buf.references()` will create a new qf list, type `<` can go to the older list.

**Comment by perseoGI** [comment]
Oh nice!
Is that a native mapping or is it binded by your plugin?

**Comment by kevinhwang91** [comment]
plugin. Just do a little enhancement.

**Comment by perseoGI** [comment]
Cool, and have you consider the possibility of storing a QF list by its name and access them?
Could be dope :)

**Comment by kevinhwang91** [comment]
I don't know what's the use case for this feature, please show me a workflow to understand how it is important.

**Comment by perseoGI** [comment]
Well, it is maybe a complex workflow but, for example, in my work right now, I have to review multiple lines of code and after a long purge and filtering on the QF list, I manage to create the QF list with all the instances to be reviewed.
Saddly, the QF lists are cleared after exiting nvim. This review process will take me maybe a week so it will be nice to store it somehow.
I know mksession could do the job, but its maybe an old and overkill solution...

**Comment by kevinhwang91** [comment]
Look like you need to persist the qf list result that doesn't make sense for your workflow. What you need is to use global marks `m[A-Z]` and populate them into qf list when you need them.
