### ISSUE TITLE
Allow defining own functions in the func_map

### ISSUE THREAD

**Issue by naquad** [kevinhwang91/nvim-bqf#79]
### Feature description

I would like to be able to define my own actions. Currently, bqf supports only a list of functions defined in `lua/bqf/keymap.lua` table `actionFuncref` which can't be modified.

So, for example, if I would like to define a split function that wouldn't close the quick fix window I would have to do my own autocmd that will be binding the keys which is quite clumsy.

### Describe the solution you'd like

Add `func_ref` key to the configuration that will allow users to define their own functions and then just merge it into the `autoFuncref`.

**Comment by kevinhwang91** [comment]
https://github.com/kevinhwang91/nvim-bqf/issues/39

**Comment by naquad** [comment]
Well, the point was exactly to avoid such constructs.
