### ISSUE TITLE
The command `bd` seems to close vim when a quickfix exists.

### ISSUE THREAD

**Issue by pittcat** [kevinhwang91/nvim-bqf#8]
- `nvim --version`:
NVIM v0.5.0-dev+1133-g0869cbd55
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az49-948

- Operating system/version:
Arch Linux

https://user-images.githubusercontent.com/22888402/111274291-cb958e00-866f-11eb-9bde-fdc23975bb01.mp4

**Comment by pittcat** [comment]
The problem doesn't exists on nvim-0.4.4.

**Comment by kevinhwang91** [comment]
It's a feature.
1. When a tabpage only contains a single quickfix window, bqf will close the quickfix window. So the tabpage will be closed. (nvim will exit if only single tabpage)
2. When `filewinid` = 0 for a location window, bqf will close the orphan location window.

I will leave this issue open. If someone hates this feature, please convince me to add an option to disable it.

**Comment by cogig** [comment]
Some users like myself may not use tagepage very often, but rather use "buffer" to simulate the said "tabpage". It might be better to add an option as an opening light for this feature.

**Comment by kevinhwang91** [comment]
> Some users like myself may not use tagepage very often, but rather use "buffer" to simulate the said "tabpage". It might be better to add an option as an opening light for this feature.

Without this feature, your single tabpage will leave a single quickfix window or an orphan location window.

**Comment by kevinhwang91** [comment]
If the current quickfix window is the only window in the only tabpage, maybe we should create a window with an empty buffer and close quickfix window instead of exiting nvim.

If you like the idea, please thumb up, otherwise thumb down.

**Comment by kevinhwang91** [comment]
Merged

**Comment by pitkling** [comment]
Sorry for bringing this up again, but is there an option or such to activate the old behavior? I would prefer vim to close when I close the last buffer (e.g., via `:q`) and only a quick fix window remains. I originally used vim-qf for exactly this feature, but together with nvim-bqf it no longer works. I expect the creation of the window with the empty buffer as you describe above prevents vim-qf from closing vim.

**Comment by kevinhwang91** [comment]
It's a bug, not a feature, you should extend your qf filetype by yourself.
