### ISSUE TITLE
winbar (neovim 0.8.0) awareness: off-by-one error in the preview window location 

### ISSUE THREAD

**Issue by wookayin** [kevinhwang91/nvim-bqf#81]
### Neovim version (nvim -v | head -n1)

nvim 0.8.0+

### Operating system/version

agnostic

### How to reproduce the issue

1. Configure winbar: `vim.opt_global.winbar = "some winbar"`
2. Open a quickfix window and launch the preview window

### Expected behavior

Just like when winbar is not used, the window border between the quickfix window and the window above should be visible and not hidden by the preview floating window.

![without winbar](https://user-images.githubusercontent.com/1009873/198855921-cbcbcd11-c4a1-463a-be7c-6909fae61673.png)

### Actual behavior

(when winbar is used) The border is hidden by the floating preview window.

![with winbar](https://user-images.githubusercontent.com/1009873/198855881-77d216da-4c8b-4734-bb1c-f1edfd20029e.png)

**Comment by wookayin** [comment]
Corner case  -- I think this will throw an error for neovim 0.7.0.  We may add `vim.fn.exists("+winbar") > 0` somewhere.

```
E5108: Error executing lua .../.vim/plugged/nvim-bqf/lua/bqf/preview/floatwin.lua:55: Invalid option name: 'winbar'
stack traceback:
        [C]: in function '__index'
        .../.vim/plugged/nvim-bqf/lua/bqf/preview/floatwin.lua:55: in function 'calculateWinOpts'
```

**Comment by kevinhwang91** [comment]
My bad, forget the older version.
