### ISSUE TITLE
Ability to sort the results

### ISSUE THREAD

**Issue by Integralist** [kevinhwang91/nvim-bqf#85]
### Feature description

Before using `:cn` to iterate through the quickfix window it would be nice if there was an option I could set to first sort the results because it helps me to know how far into the list I'm am (at a glance).

### Describe the solution you'd like

```lua
.setup({
  sort_items = true,
})
```

Or maybe a command that I can alias to a keymap (e.g. `:BqfSort`)

### Additional context

Another reason for sorting is because I want to deal with all the issues with a file at once.

So looking at the below screenshot you can see `custom_tls_activation_test.go` is listed, and there there are a couple of other items from separate files, but then `custom_tls_activation_test.go` pops up again.

<img width="943" alt="Screenshot 2022-10-31 at 16 35 24" src="https://user-images.githubusercontent.com/180050/199060641-4ee10c75-0b08-49f0-a040-5b87c1705c2e.png">

**Comment by kevinhwang91** [comment]
Make sense, but will consume the extra computation of list sort, should provide an upper limit value for the user. I will imp this feature later.

**Comment by kevinhwang91** [comment]
```lua
function _G.qfSort()
    local items = fn.getqflist()
    table.sort(items, function(a, b)
        if a.bufnr == b.bufnr then
            if a.lnum == b.lnum then
                return a.col < b.col
            else
                return a.lnum < b.lnum
            end
        else
            return a.bufnr < b.bufnr
        end
    end)
    fn.setqflist(items, 'r')
end
```
This script should work. I found to sort the list automatically is invasive in a plugin, user should sort the list by themselves.
