### ISSUE TITLE
Apply quickfix

### ISSUE THREAD

**Issue by Curs3W4ll** [kevinhwang91/nvim-bqf#86]
### Feature description

Make possible to apply the quickfix directly from the quickfix window

### Describe the solution you'd like

Bind a key to a function that apply the quickfix for the current line if any.  
So do not have anymore to hit Enter (or o) to go to the line of the quickfix and then apply it.  
Directly apply the quickfix inside the quickfix window.

**Comment by kevinhwang91** [comment]
I don't understand the `apply`, you mean to set the current index to the item under the cursor?

**Comment by Curs3W4ll** [comment]
Often, items in quickfix have an autofix that coc can apply itself.  
But I don't know any way to apply this autofix directly inside the quickfix window

**Comment by kevinhwang91** [comment]
Yes, `quickfix` in coc.nvim and Vscode is not the same as in Neovim and Vim.

Must inject actions into quickfix window for users.

**Comment by Curs3W4ll** [comment]
Oh I understand,

So I need to ask this to coc, not you right ?

Sorry for the inconveniance
