### ISSUE TITLE
Disable nvim-hlslens like side marks

### ISSUE THREAD

**Issue by anuvyklack** [kevinhwang91/nvim-bqf#87]
### Neovim version (nvim -v | head -n1)

-

### Operating system/version

-

### How to reproduce the issue

Some time ago in the preview window appears side marks like in nvim-hlslens plugin. Like `[35/54]` and so on. How to turn them off? I didn't find a configuration option, and they are distracting for me.

### Expected behavior

-

### Actual behavior

-

**Comment by kevinhwang91** [comment]
Make sense. I will add the option later.
