### ISSUE TITLE
Paste into zf search box

### ISSUE THREAD

**Issue by yashamon** [kevinhwang91/nvim-bqf#88]
### Feature description

The fzf based zf search box currently does not seem to allow pasting. 

### Describe the solution you'd like

Add some paste capability. For example using the standard <C-R>+

**Comment by kevinhwang91** [comment]
Make sense, I also need it.

**Comment by kevinhwang91** [comment]
Found that we can remap by ourselves, shouldn't add this feature in bqf.
```lua
vim.keymap.set('t', '<C-r>+', [[getreg('+')]], {expr = true})
```

**Comment by yashamon** [comment]
Thanks!
