### ISSUE TITLE
Is there a way to disable syntax highlighting completely?

### ISSUE THREAD

**Issue by joshua7v** [kevinhwang91/nvim-bqf#89]
### Feature description

Hi, the question might be a bit unusual, sorry about that.
but I wonder if I can disable the syntax highlighting completely within preview
I use `syntax manual` daily and don't have treesitter installed
I aslo cannot just do `syntax off`, because I still need something highlighted sometimes (like highlight filename in quickfix)

I tried to give `setlocal syntax=off` to floating windows, but with no luck to make it work.

```
" my setting
syntax manual
autocmd FileType dirvish,qf setlocal syntax=on

" what I tried but not work
autocmd BufWinEnter,WinNew * if nvim_win_get_config(0)['relative'] != '' | setlocal syntax=off | endif
```

### Describe the solution you'd like

Maybe provide some suggestions? that would be very helpful.

**Comment by kevinhwang91** [comment]
You are crazy!

**Comment by joshua7v** [comment]
@kevinhwang91 LOL  I know its a bit wwweird, but thanks, works great.
