### ISSUE TITLE
Error occurred when pressing 'zf'

### ISSUE THREAD

**Issue by qqlearn123** [kevinhwang91/nvim-bqf#92]
### Feature description

I encounted an error when press 'zf' in quickfix window. The error message is as follows:

_E5108: Error executing lua ...vim/site/pack/packer/opt/nvim-bqf/lua/bqf/filter/fzf.lua: 583: fzf#run function not found. You also need Vim plugin from the main fzf repository._

Environment setup: I am using nvim-bqf in nvim. Since I am using telescope from nvim, fzf is not installed as a nvim plugin. But I do have fzf and fzf.vim installed as vim plugins (installed through vim) and fzf command is available in my PATH, and I use fzf on daily basis in terminal without any issues.

Is this error due to missing the fzf plugin in nvim?

### Describe the solution you'd like

Is it possible that as long as I have fzf command available in terminal (no matter how it is installed, whether through vim, nvim or apt install or go install), the nvim-bqf plugin will be able to use it?

**Comment by kevinhwang91** [comment]
bqf needs `plugin/fzf.vim`, no idea how to find this path.
`pacman -Ql fzf | rg fzf.vim` output `fzf /usr/share/vim/vimfiles/plugin/fzf.vim`

**Comment by qqlearn123** [comment]
> bqf needs `plugin/fzf.vim`, no idea how to find this path. `pacman -Ql fzf | rg fzf.vim` output `fzf /usr/share/vim/vimfiles/plugin/fzf.vim`

My fzf executable is this path '~/.vim/plugged/fzf/bin/fzf' and fzf.vim is here '~/.vim/plugged/fzf.vim'.

Since I am using the nvim-bqf package inside nvim, there is no way around for it to use fzf installed with vim?

**Comment by kevinhwang91** [comment]
`so ~/.vim/plugged/fzf.vim` by yourself.

**Comment by qqlearn123** [comment]
> `so ~/.vim/plugged/fzf.vim` by yourself.

Sorry, I did not quite follow. What is the solution and what am I supposed to do here?

**Comment by kevinhwang91** [comment]
Load `fzf.vim` before bqf calling fzf by yourself. `:h so`

**Comment by qqlearn123** [comment]
> Load `fzf.vim` before bqf calling fzf by yourself. `:h so`

Tried so ~/.vim/plugged/fzf.vim, but got an error saying cannot source a directory.

**Comment by kevinhwang91** [comment]
Maybe in `~/.config/nvim/after/ftplugin/qf.lua`
```lua
if vim.b.bqf_enabled then
    vim.cmd('so ~/.vim/plugged/fzf.vim')
end
```
