### ISSUE TITLE
Add option to fzf automatically 

### ISSUE THREAD

**Issue by yashamon** [kevinhwang91/nvim-bqf#94]
### Feature description

If I execute the code chunk

     vim.cmd('copen')
     vim.fn.feedkeys("zf")

I get an error about some nil pointer, this is probably because of some race condition.
The hack solution is to add a delay

    vim.cmd('copen')
    vim.cmd('sleep 600m')
    vim.fn.feedkeys("zf")

### Describe the solution you'd like

Certainly, it would be nice to have some option to auto zf.

**Comment by kevinhwang91** [comment]
```lua
if vim.b.bqf_enabled then
    vim.defer_fn(function()
        vim.api.nvim_feedkeys('zf', 'im', false)
    end, 10)
end
```

**Comment by yashamon** [comment]
This does not work probably because the condition vim.b.bqf_enabled is
false, it works if you sleep first

**Comment by yashamon** [comment]
Oh nevermind it doesn't work with sleep either.  Which is weird. Also timeout has the same problem as before doesn't it?

**Comment by yashamon** [comment]
On further testing. It works if timeout is 400 instead of 10.
However, this is the same problem as with sleep before. It is better to have a built in solution that does not require timing or race conditions.

**Comment by yashamon** [comment]
It works if the quickfix list is small. Otherwise you have to set timeout
to be much larger. Or you get desync again.

For reference telescope does what we are looking for, however telescope has
a different problem: it becomes slow on large files.

**Comment by kevinhwang91** [comment]
`dev` branch should fix this issue. Please switch branch and follow below code snippet:

```lua
-- Two options:
-- 1. under your_path/after/ftplugin/qf.lua
if vim.w.bqf_enabled then
    vim.api.nvim_feedkeys('zf', 'im', false)
end

-- 2. otherwise, make sure bqf is fired
if vim.w.bqf_enabled then
    local winid = vim.api.nvim_get_current_win()
    vim.schedule(function()
        vim.api.nvim_win_call(winid, function()
            vim.api.nvim_feedkeys('zf', 'im', false)
        end)
    end)
end
```

**Comment by yashamon** [comment]
Sweet, the first option is working.

**Comment by kevinhwang91** [comment]
Merged to main.

**Comment by yashamon** [comment]
Thanks a lot.

Another question, is it possible to refine the quickfix/locationlist on
some <hotkey> after fzf. So :copen<cr>zfsearchpattern<hotkey>, now the
quickfix list contains only items matching searchpattern.

**Comment by kevinhwang91** [comment]
```lua
if vim.w.bqf_enabled then
    local savedOpts = vim.env.FZF_DEFAULT_OPTS
    vim.env.FZF_DEFAULT_OPTS = vim.env.FZF_DEFAULT_OPTS .. ' -q pattern'
    vim.api.nvim_feedkeys('zf', 'im', false)
    vim.api.nvim_create_autocmd('FileType', {
        pattern = 'fzf',
        once = true,
        callback = function()
            vim.env.FZF_DEFAULT_OPTS = savedOpts
        end
    })
end
```

**Comment by yashamon** [comment]
I don't understand what that does, but I probably wasn't clear. Let's say
our <hotkey>=<cr>
So after executing :copen<cr>zfBlah<cr>
now the quickfix list only contains items filtered by fzf with pattern Blah
If I do :copen<cr> I get the prefiltered quickfix list.
This is useful to use with commands like cn, lne so they will refer to the
already filtered list.

**Comment by kevinhwang91** [comment]
Will work. `man fzf` and then search `--query` and `ENVIRONMENT VARIABLES`

**Comment by yashamon** [comment]
I tested it, it just make it so that the search now starts with 'pattern'
pre entered. I want the quickfix list to be rewritten/updated.

**Comment by kevinhwang91** [comment]
`h cfilter`

**Comment by yashamon** [comment]
cfilter is not what I am looking for. Like I said, I want to rewrite the
quickfixlist/locationlist. So somewhere we have to call setloclist("fzf
filtered list")

**Comment by kevinhwang91** [comment]
Can't get your point, hack yourself or more details.

**Comment by yashamon** [comment]
I am not a programmer.

I want zfpattern to rewrite quickfixlist, so it consists of pattern matched
items. maybe with a shortcut.

I should say that fzf already may have API for this:. it can send its lists
to loclists, I just don't know how to use it.

cfilter may also rewrite, but that does not involve fzf matching.

**Comment by kevinhwang91** [comment]
I don't know why you must use fzf pattern, I can't image the use case.

**Comment by yashamon** [comment]
In my case, editing latex or prose. For example, I have
a script which
sends all sentences (not lines) in latex file to a loclist. Open with
bqf fzf search 'pattern', and get all sentences matching
pattern. It would often help to rewrite the loclist,
then the matched sentences can be navigated with lnext,
lprev commands.

**Comment by kevinhwang91** [comment]
You misunderstand my question. Why must use fzf pattern instead of cfilter?

**Comment by yashamon** [comment]
Didn't I already answer this question?
The same reason one always uses fzf, visually confirmed fuzzy matching. Is
cfilter even fuzzy match? I think it is just grep.

Also, running cfilter means having to enter extra commands. The list is
already there, just send it to the new location list with a keystroke.

**Comment by kevinhwang91** [comment]
No idea how to achieve it.

**Comment by yashamon** [comment]
Ok, thanks for considering it.
