### ISSUE TITLE
Jump to origin line with quickfix close open action

### ISSUE THREAD

**Issue by P2Tree** [kevinhwang91/nvim-bqf#95]
### Neovim version (nvim -v | head -n1)

NVIM 0.8.1

### Operating system/version

Ubuntu 18.04

### How to reproduce the issue

1. open quickfix
2. use 'openc' or 'drop' to toggle an item with objective line that is different with the current cursor line.

### Expected behavior

I expected the cursor will jump to the objective line I selected. And quickfix window will close.

### Actual behavior

I got a quick jump to the objective line and then jump returned to the origin line.

An example is when my cursor is located at 100 and I open quickfix and select an item which willing to jump to 50, I got the cursor jump to 50 and then jump to 100 immediately.

This behavior only happened in 'openc' and 'drop', which I think is jump with quickfix window close automatically.

I am not sure this is a bug or drawback something, maybe this is a conflict with my other plugins. I tried to disable as possible as other plugins and this issue still exists.

**Comment by kevinhwang91** [comment]
Must be your config issue. Can't reproduce it, pls debug yourself.
