### ISSUE TITLE
A reasonable way to remove an entry from the list

### ISSUE THREAD

**Issue by RayZ0rr** [kevinhwang91/nvim-bqf#99]
### Feature description

I really love this plugin for major refactoring and bugfixing. I am looking for ways to make it more convenient. One of the quality of life changes is the ability to remove an entry (one at a time). Possible methods are listed below.

As I believe you are an expert when it comes to quickfix window, could you suggest what do you think is the most reasonable? Just a suggestion, no accountability for actions thereafter. Maybe a ranking of preferred order?

1. `vim.keymap.set('n','dd' , '<tab>zN',{buffer=true,desc="qf delete entry"})`
2. [quickfix-dd](https://github.com/TamaMcGlinn/quickfixdd) from [this StackOverflow answer](https://stackoverflow.com/a/48817071)
3. `nnoremap <buffer> <silent> dd <Cmd>call setqflist(filter(getqflist(), {idx -> idx != line('.') - 1}), 'r') <Bar> cc<CR>` from the same StackOverflow thread as above. ([this StackOverflow](https://vi.stackexchange.com/questions/21254/visual-delete-items-from-quickfix-list) addresses a modified version which allows visual selection).
4. `:set modifiable<cr>dd:cgetbuffer<cr>` from [this](https://www.reddit.com/r/vim/comments/7dv9as/how_to_edit_the_vim_quickfix_list/) reddit post.

Thanks.

### Describe the solution you'd like

Maybe this post will help people who request such a feature in the future.

**Comment by kevinhwang91** [comment]
IMO, bqf shouldn't do the hack for this feature because qf buffer shouldn't be modified. Adding a sign for items and then creating a new qf list is a safe workflow.
However, users should hack by themselves.

**Comment by RayZ0rr** [comment]
Yes, I understand. But I wanted to know your opinion on which of the methods mentioned above seemed safe?

> As I believe you are an expert when it comes to quickfix window, could you suggest what do you think is the most reasonable? Just a suggestion, no accountability for actions thereafter. Maybe a ranking of preferred order?

**Comment by kevinhwang91** [comment]
The first option is implemented by bqf which will always create a new qf list after "delete" an item.
The second and the third options are the same which will replace the original qf list which means you can't undo the deleted item.
The fourth option is very invasive and doesn't work for me.
